import type { Recipe } from "./types"

// Recipe database with complete ingredients for meal planning
export const sampleRecipes: Recipe[] = [
  {
    id: "1",
    name: "Pancakes",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/fluffy-pancakes-with-syrup.jpg",
    ingredients: [
      { id: "1-1", name: "flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "1-2", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "1-3", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "1-4", name: "baking powder", amount: 1, unit: "tsp", category: "pantry" },
      { id: "1-5", name: "sugar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "1-6", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "1-7", name: "vanilla extract", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Mix dry ingredients", "Add wet ingredients", "Cook on griddle"],
    nutrition: { calories: 350, protein: 8, carbs: 45, fat: 15 },
    cost: 5.5,
  },
  {
    id: "2",
    name: "French Toast",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    image: "/french-toast-with-berries.jpg",
    ingredients: [
      { id: "2-1", name: "bread", amount: 8, unit: "slice", category: "pantry" },
      { id: "2-2", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "2-3", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "2-4", name: "cinnamon", amount: 1, unit: "tsp", category: "pantry" },
      { id: "2-5", name: "vanilla extract", amount: 1, unit: "tsp", category: "pantry" },
      { id: "2-6", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "2-7", name: "maple syrup", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Whisk eggs and milk", "Dip bread", "Cook until golden"],
    nutrition: { calories: 320, protein: 12, carbs: 42, fat: 12 },
    cost: 4.5,
  },
  {
    id: "3",
    name: "Waffles",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/belgian-waffles-breakfast.jpg",
    ingredients: [
      { id: "3-1", name: "flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "3-2", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "3-3", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "3-4", name: "baking powder", amount: 1, unit: "tsp", category: "pantry" },
      { id: "3-5", name: "sugar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "3-6", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "3-7", name: "vanilla extract", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Mix ingredients", "Cook in waffle iron"],
    nutrition: { calories: 380, protein: 9, carbs: 48, fat: 17 },
    cost: 6.0,
  },
  {
    id: "4",
    name: "Eggs Benedict",
    category: "breakfast",
    diet: "classic",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    image: "/eggs-benedict-hollandaise.png",
    ingredients: [
      { id: "4-1", name: "english muffins", amount: 2, unit: "whole", category: "pantry" },
      { id: "4-2", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "4-3", name: "canadian bacon", amount: 1, unit: "lb", category: "meat" },
      { id: "4-4", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "4-5", name: "lemon juice", amount: 2, unit: "tbsp", category: "produce" },
      { id: "4-6", name: "cayenne pepper", amount: 1, unit: "tsp", category: "pantry" },
      { id: "4-7", name: "hollandaise sauce", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Poach eggs", "Toast muffins", "Assemble with hollandaise"],
    nutrition: { calories: 520, protein: 24, carbs: 28, fat: 35 },
    cost: 8.5,
  },
  {
    id: "5",
    name: "Omelette",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    image: "/fluffy-omelette-vegetables.jpg",
    ingredients: [
      { id: "5-1", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "5-2", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "5-3", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "5-4", name: "vegetables", amount: 1, unit: "cup", category: "produce" },
      { id: "5-5", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "5-6", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Beat eggs", "Cook in butter", "Add fillings and fold"],
    nutrition: { calories: 320, protein: 22, carbs: 4, fat: 25 },
    cost: 3.5,
  },
  {
    id: "6",
    name: "Scrambled Eggs",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    image: "/scrambled-eggs-breakfast.jpg",
    ingredients: [
      { id: "6-1", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "6-2", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "6-3", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "6-4", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "6-5", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Beat eggs with milk", "Cook in butter", "Stir until fluffy"],
    nutrition: { calories: 250, protein: 18, carbs: 3, fat: 19 },
    cost: 2.5,
  },
  {
    id: "7",
    name: "Poached Eggs",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    image: "/poached-eggs-toast.jpg",
    ingredients: [
      { id: "7-1", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "7-2", name: "water", amount: 1, unit: "cup", category: "pantry" },
      { id: "7-3", name: "vinegar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "7-4", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Boil water with vinegar", "Crack eggs gently", "Cook until set"],
    nutrition: { calories: 140, protein: 12, carbs: 1, fat: 10 },
    cost: 1.5,
  },
  {
    id: "8",
    name: "Fried Eggs",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 2,
    cookTime: 5,
    servings: 2,
    image: "/fried-eggs-sunny-side-up.jpg",
    ingredients: [
      { id: "8-1", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "8-2", name: "oil or butter", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "8-3", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "8-4", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Heat oil", "Crack eggs", "Cook to desired doneness"],
    nutrition: { calories: 180, protein: 12, carbs: 1, fat: 14 },
    cost: 1.5,
  },
  {
    id: "9",
    name: "Boiled Eggs",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 2,
    cookTime: 10,
    servings: 4,
    image: "/boiled-eggs.jpg",
    ingredients: [
      { id: "9-1", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "9-2", name: "water", amount: 1, unit: "cup", category: "pantry" },
      { id: "9-3", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Boil water", "Add eggs", "Cook 6-12 minutes"],
    nutrition: { calories: 140, protein: 12, carbs: 1, fat: 10 },
    cost: 1.0,
  },
  {
    id: "10",
    name: "Avocado Toast",
    category: "breakfast",
    diet: "vegan",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    image: "/avocado-toast.png",
    ingredients: [
      { id: "10-1", name: "bread", amount: 2, unit: "slice", category: "pantry" },
      { id: "10-2", name: "avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "10-3", name: "lemon juice", amount: 2, unit: "tbsp", category: "produce" },
      { id: "10-4", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "10-5", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
      { id: "10-6", name: "red pepper flakes (optional)", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Toast bread", "Mash avocado", "Spread and season"],
    nutrition: { calories: 280, protein: 6, carbs: 28, fat: 18 },
    cost: 4.0,
  },
  {
    id: "11",
    name: "Grilled Chicken",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/grilled-chicken-breast.png",
    ingredients: [
      { id: "11-1", name: "chicken breast", amount: 1, unit: "lb", category: "meat" },
      { id: "11-2", name: "olive oil", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "11-3", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "11-4", name: "lemon", amount: 1, unit: "whole", category: "produce" },
      { id: "11-5", name: "herbs", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "11-6", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "11-7", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Marinate chicken", "Grill until cooked through"],
    nutrition: { calories: 280, protein: 35, carbs: 2, fat: 14 },
    cost: 8.0,
  },
  {
    id: "12",
    name: "Roast Beef",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 90,
    servings: 6,
    image: "/roast-beef-dinner.jpg",
    ingredients: [
      { id: "12-1", name: "beef roast", amount: 2, unit: "lb", category: "meat" },
      { id: "12-2", name: "olive oil", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "12-3", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "12-4", name: "rosemary", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "12-5", name: "thyme", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "12-6", name: "salt", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "12-7", name: "pepper", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season beef", "Roast at 350°F", "Rest before slicing"],
    nutrition: { calories: 420, protein: 45, carbs: 1, fat: 25 },
    cost: 15.0,
  },
  {
    id: "13",
    name: "Lamb Chops",
    category: "dinner",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/grilled-lamb-chops.jpg",
    ingredients: [
      { id: "13-1", name: "lamb chops", amount: 1, unit: "lb", category: "meat" },
      { id: "13-2", name: "olive oil", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "13-3", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "13-4", name: "rosemary", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "13-5", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "13-6", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Season chops", "Sear in hot pan", "Finish in oven"],
    nutrition: { calories: 380, protein: 32, carbs: 1, fat: 28 },
    cost: 12.0,
  },
  {
    id: "14",
    name: "Pork Tenderloin",
    category: "dinner",
    diet: "classic",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    image: "/pork-tenderloin-roasted.jpg",
    ingredients: [
      { id: "14-1", name: "pork tenderloin", amount: 1, unit: "lb", category: "meat" },
      { id: "14-2", name: "olive oil", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "14-3", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "14-4", name: "herbs", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "14-5", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
      { id: "14-6", name: "pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Season pork", "Sear all sides", "Roast until done"],
    nutrition: { calories: 320, protein: 38, carbs: 2, fat: 17 },
    cost: 10.0,
  },
  {
    id: "15",
    name: "Pad Thai",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    image: "/pad-thai-noodles.png",
    ingredients: [
      { id: "15-1", name: "rice noodles", amount: 8, unit: "oz", category: "pantry" },
      { id: "15-2", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "15-3", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "15-4", name: "bean sprouts", amount: 1, unit: "cup", category: "produce" },
      { id: "15-5", name: "peanuts", amount: 1, unit: "cup", category: "pantry" },
      { id: "15-6", name: "lime", amount: 2, unit: "whole", category: "produce" },
      { id: "15-7", name: "fish sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "15-8", name: "tamarind paste", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Soak noodles", "Stir-fry ingredients", "Toss with sauce"],
    nutrition: { calories: 450, protein: 28, carbs: 52, fat: 15 },
    cost: 12.0,
  },
  {
    id: "16",
    name: "Tom Yum Soup",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/tom-yum-soup-thai.jpg",
    ingredients: [
      { id: "16-1", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "16-2", name: "lemongrass", amount: 2, unit: "stalk", category: "produce" },
      { id: "16-3", name: "galangal", amount: 1, unit: "inch", category: "produce" },
      { id: "16-4", name: "kaffir lime leaves", amount: 4, unit: "whole", category: "produce" },
      { id: "16-5", name: "mushrooms", amount: 1, unit: "cup", category: "produce" },
      { id: "16-6", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "16-7", name: "fish sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "16-8", name: "lime juice", amount: 2, unit: "tbsp", category: "produce" },
    ],
    instructions: ["Boil aromatics", "Add shrimp and vegetables", "Season and serve"],
    nutrition: { calories: 180, protein: 24, carbs: 12, fat: 4 },
    cost: 10.0,
  },
  {
    id: "17",
    name: "Green Curry",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    image: "/green-curry-thai.jpg",
    ingredients: [
      { id: "17-1", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "17-2", name: "green curry paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "17-3", name: "coconut milk", amount: 1, unit: "can", category: "pantry" },
      { id: "17-4", name: "bamboo shoots", amount: 1, unit: "cup", category: "produce" },
      { id: "17-5", name: "thai basil", amount: 1, unit: "cup", category: "produce" },
      { id: "17-6", name: "fish sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "17-7", name: "palm sugar", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Fry curry paste", "Add coconut milk", "Simmer with chicken"],
    nutrition: { calories: 420, protein: 28, carbs: 18, fat: 28 },
    cost: 11.0,
  },
  {
    id: "18",
    name: "Fried Rice",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/fried-rice-asian.jpg",
    ingredients: [
      { id: "18-1", name: "rice", amount: 3, unit: "cup", category: "pantry" },
      { id: "18-2", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "18-3", name: "vegetables", amount: 2, unit: "cup", category: "produce" },
      { id: "18-4", name: "soy sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "18-5", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "18-6", name: "oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Scramble eggs", "Stir-fry rice", "Add vegetables and sauce"],
    nutrition: { calories: 380, protein: 12, carbs: 58, fat: 12 },
    cost: 6.0,
  },
  {
    id: "19",
    name: "Ramen",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    image: "/ramen-noodle-soup.jpg",
    ingredients: [
      { id: "19-1", name: "ramen noodles", amount: 2, unit: "pack", category: "pantry" },
      { id: "19-2", name: "pork belly", amount: 1, unit: "lb", category: "meat" },
      { id: "19-3", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "19-4", name: "green onions", amount: 2, unit: "stalk", category: "produce" },
      { id: "19-5", name: "nori", amount: 2, unit: "sheet", category: "pantry" },
      { id: "19-6", name: "broth", amount: 4, unit: "cup", category: "pantry" },
      { id: "19-7", name: "soy sauce", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Prepare broth", "Cook noodles", "Assemble with toppings"],
    nutrition: { calories: 520, protein: 32, carbs: 48, fat: 22 },
    cost: 9.0,
  },
  {
    id: "20",
    name: "Sushi",
    category: "lunch",
    diet: "classic",
    prepTime: 30,
    cookTime: 0,
    servings: 2,
    image: "/sushi-rolls-platter.jpg",
    ingredients: [
      { id: "20-1", name: "sushi rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "20-2", name: "nori", amount: 4, unit: "sheet", category: "pantry" },
      { id: "20-3", name: "fish", amount: 1, unit: "lb", category: "meat" },
      { id: "20-4", name: "avocado", amount: 1, unit: "whole", category: "produce" },
      { id: "20-5", name: "cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "20-6", name: "rice vinegar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "20-7", name: "soy sauce", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Prepare rice", "Roll with fillings", "Slice and serve"],
    nutrition: { calories: 350, protein: 18, carbs: 52, fat: 8 },
    cost: 14.0,
  },
  {
    id: "21",
    name: "Dal Makhani",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    image: "/dal-makhani-indian.jpg",
    ingredients: [
      { id: "21-1", name: "black lentils", amount: 1, unit: "cup", category: "pantry" },
      { id: "21-2", name: "kidney beans", amount: 1, unit: "cup", category: "pantry" },
      { id: "21-3", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "21-4", name: "cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "21-5", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "21-6", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "21-7", name: "garam masala", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Soak and cook lentils", "Prepare tomato base", "Simmer with cream"],
    nutrition: { calories: 380, protein: 18, carbs: 42, fat: 16 },
    cost: 7.0,
  },
  {
    id: "22",
    name: "Butter Chicken",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    image: "/butter-chicken-curry.jpg",
    ingredients: [
      { id: "22-1", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "22-2", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "22-3", name: "cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "22-4", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "22-5", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "22-6", name: "garam masala", amount: 1, unit: "tsp", category: "pantry" },
      { id: "22-7", name: "kasuri methi", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Marinate chicken", "Cook in tomato sauce", "Add cream and butter"],
    nutrition: { calories: 450, protein: 32, carbs: 18, fat: 28 },
    cost: 10.0,
  },
  {
    id: "23",
    name: "Palak Paneer",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    image: "/palak-paneer-spinach.jpg",
    ingredients: [
      { id: "23-1", name: "spinach", amount: 2, unit: "lb", category: "produce" },
      { id: "23-2", name: "paneer", amount: 1, unit: "lb", category: "dairy" },
      { id: "23-3", name: "cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "23-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "23-5", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "23-6", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "23-7", name: "garam masala", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Blanch spinach", "Prepare gravy", "Add paneer and cream"],
    nutrition: { calories: 380, protein: 22, carbs: 24, fat: 22 },
    cost: 8.0,
  },
  {
    id: "24",
    name: "Chicken Biryani",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 60,
    servings: 6,
    image: "/chicken-biryani-rice.jpg",
    ingredients: [
      { id: "24-1", name: "basmati rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "24-2", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "24-3", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "24-4", name: "onions", amount: 3, unit: "whole", category: "produce" },
      { id: "24-5", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "24-6", name: "biryani masala", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "24-7", name: "saffron", amount: 1, unit: "tsp", category: "pantry" },
      { id: "24-8", name: "ghee", amount: 3, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Marinate chicken", "Layer rice and chicken", "Dum cook"],
    nutrition: { calories: 520, protein: 28, carbs: 62, fat: 18 },
    cost: 12.0,
  },
  {
    id: "25",
    name: "Masala Dosa",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    image: "/masala-dosa-crispy.jpg",
    ingredients: [
      { id: "25-1", name: "dosa batter", amount: 2, unit: "cup", category: "pantry" },
      { id: "25-2", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "25-3", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "25-4", name: "green chilies", amount: 3, unit: "whole", category: "produce" },
      { id: "25-5", name: "mustard seeds", amount: 1, unit: "tsp", category: "pantry" },
      { id: "25-6", name: "curry leaves", amount: 10, unit: "whole", category: "produce" },
      { id: "25-7", name: "turmeric", amount: 1, unit: "tsp", category: "pantry" },
      { id: "25-8", name: "oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Prepare potato filling", "Spread dosa batter", "Fill and fold"],
    nutrition: { calories: 320, protein: 8, carbs: 58, fat: 8 },
    cost: 5.0,
  },
  {
    id: "26",
    name: "Chole Bhature",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    image: "/chole-bhature-chickpeas.jpg",
    ingredients: [
      { id: "26-1", name: "chickpeas", amount: 2, unit: "cup", category: "pantry" },
      { id: "26-2", name: "flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "26-3", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "26-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "26-5", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "26-6", name: "ginger", amount: 2, unit: "inch", category: "produce" },
      { id: "26-7", name: "garlic", amount: 6, unit: "clove", category: "produce" },
      { id: "26-8", name: "chole masala", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "26-9", name: "oil", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: [
      "Soak chickpeas overnight and pressure cook",
      "Prepare chole masala gravy with onions, tomatoes, and spices",
      "Make bhature dough with flour, yogurt, and let it rest",
      "Roll and deep fry bhature until puffed and golden",
      "Serve hot chole with bhature, onions, and pickle",
    ],
    nutrition: { calories: 480, protein: 16, carbs: 68, fat: 16 },
    cost: 6.0,
  },
  {
    id: "27",
    name: "Bagel with Cream Cheese",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    image: "/bagel-cream-cheese.jpg",
    ingredients: [
      { id: "27-1", name: "bagels", amount: 2, unit: "whole", category: "pantry" },
      { id: "27-2", name: "cream cheese", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "27-3", name: "smoked salmon (optional)", amount: 2, unit: "oz", category: "meat" },
      { id: "27-4", name: "capers", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "27-5", name: "red onion", amount: 1, unit: "slice", category: "produce" },
    ],
    instructions: ["Toast bagels", "Spread cream cheese", "Add toppings"],
    nutrition: { calories: 320, protein: 12, carbs: 48, fat: 10 },
    cost: 4.5,
  },
  {
    id: "28",
    name: "Breakfast Burrito",
    category: "breakfast",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/breakfast-burrito.jpg",
    ingredients: [
      { id: "28-1", name: "tortillas", amount: 2, unit: "whole", category: "pantry" },
      { id: "28-2", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "28-3", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "28-4", name: "sausage", amount: 4, unit: "oz", category: "meat" },
      { id: "28-5", name: "bell peppers", amount: 1, unit: "whole", category: "produce" },
      { id: "28-6", name: "salsa", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Scramble eggs", "Cook sausage", "Wrap in tortilla"],
    nutrition: { calories: 520, protein: 28, carbs: 42, fat: 26 },
    cost: 6.5,
  },
  {
    id: "29",
    name: "Granola Bowl",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    image: "/granola-bowl.jpg",
    ingredients: [
      { id: "29-1", name: "granola", amount: 1, unit: "cup", category: "pantry" },
      { id: "29-2", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "29-3", name: "berries", amount: 1, unit: "cup", category: "produce" },
      { id: "29-4", name: "honey", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "29-5", name: "nuts", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Layer yogurt and granola", "Top with berries and honey"],
    nutrition: { calories: 380, protein: 14, carbs: 58, fat: 12 },
    cost: 5.0,
  },
  {
    id: "30",
    name: "Smoothie Bowl",
    category: "breakfast",
    diet: "vegan",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    image: "/smoothie-bowl.jpg",
    ingredients: [
      { id: "30-1", name: "frozen berries", amount: 2, unit: "cup", category: "produce" },
      { id: "30-2", name: "banana", amount: 1, unit: "whole", category: "produce" },
      { id: "30-3", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "30-4", name: "granola", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "30-5", name: "chia seeds", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Blend berries, banana, and milk", "Pour into bowl", "Top with granola and seeds"],
    nutrition: { calories: 320, protein: 10, carbs: 62, fat: 6 },
    cost: 4.5,
  },
  {
    id: "31",
    name: "Quiche",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    image: "/quiche.jpg",
    ingredients: [
      { id: "31-1", name: "pie crust", amount: 1, unit: "whole", category: "pantry" },
      { id: "31-2", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "31-3", name: "cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "31-4", name: "bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "31-5", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "31-6", name: "onions", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Prepare crust", "Mix filling", "Bake until set"],
    nutrition: { calories: 420, protein: 18, carbs: 24, fat: 28 },
    cost: 8.0,
  },
  {
    id: "32",
    name: "Croissant Sandwich",
    category: "breakfast",
    diet: "classic",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    image: "/croissant-sandwich.jpg",
    ingredients: [
      { id: "32-1", name: "croissants", amount: 2, unit: "whole", category: "pantry" },
      { id: "32-2", name: "ham", amount: 4, unit: "slice", category: "meat" },
      { id: "32-3", name: "cheese", amount: 2, unit: "slice", category: "dairy" },
      { id: "32-4", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "32-5", name: "butter", amount: 1, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Slice croissants", "Add fillings", "Toast if desired"],
    nutrition: { calories: 480, protein: 22, carbs: 38, fat: 26 },
    cost: 6.0,
  },
  {
    id: "33",
    name: "Shakshuka",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/shakshuka.jpg",
    ingredients: [
      { id: "33-1", name: "eggs", amount: 6, unit: "whole", category: "meat" },
      { id: "33-2", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "33-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "33-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "33-5", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "33-6", name: "cumin", amount: 1, unit: "tsp", category: "pantry" },
      { id: "33-7", name: "paprika", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Simmer tomato sauce", "Crack eggs on top", "Bake until set"],
    nutrition: { calories: 280, protein: 16, carbs: 18, fat: 16 },
    cost: 5.5,
  },
  {
    id: "34",
    name: "Huevos Rancheros",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/huevos-rancheros.jpg",
    ingredients: [
      { id: "34-1", name: "tortillas", amount: 2, unit: "whole", category: "pantry" },
      { id: "34-2", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "34-3", name: "black beans", amount: 1, unit: "cup", category: "pantry" },
      { id: "34-4", name: "salsa", amount: 1, unit: "cup", category: "pantry" },
      { id: "34-5", name: "avocado", amount: 1, unit: "whole", category: "produce" },
      { id: "34-6", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Warm tortillas", "Fry eggs", "Layer with beans and salsa"],
    nutrition: { calories: 480, protein: 24, carbs: 42, fat: 24 },
    cost: 6.5,
  },
  {
    id: "35",
    name: "Eggs Florentine",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    image: "/eggs-florentine.jpg",
    ingredients: [
      { id: "35-1", name: "english muffins", amount: 2, unit: "whole", category: "pantry" },
      { id: "35-2", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "35-3", name: "spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "35-4", name: "hollandaise sauce", amount: 1, unit: "cup", category: "dairy" },
      { id: "35-5", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Sauté spinach", "Poach eggs", "Assemble with hollandaise"],
    nutrition: { calories: 420, protein: 18, carbs: 28, fat: 26 },
    cost: 7.0,
  },
  {
    id: "36",
    name: "Breakfast Hash",
    category: "breakfast",
    diet: "classic",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/breakfast-hash.jpg",
    ingredients: [
      { id: "36-1", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "36-2", name: "sausage", amount: 1, unit: "lb", category: "meat" },
      { id: "36-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "36-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "36-5", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "36-6", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Dice and cook potatoes", "Add sausage and vegetables", "Top with eggs"],
    nutrition: { calories: 520, protein: 26, carbs: 42, fat: 28 },
    cost: 8.5,
  },
  {
    id: "37",
    name: "Coq au Vin",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    image: "/coq-au-vin.jpg",
    ingredients: [
      { id: "37-1", name: "chicken", amount: 1, unit: "whole", category: "meat" },
      { id: "37-2", name: "red wine", amount: 2, unit: "cup", category: "pantry" },
      { id: "37-3", name: "bacon", amount: 4, unit: "slice", category: "meat" },
      { id: "37-4", name: "mushrooms", amount: 2, unit: "cup", category: "produce" },
      { id: "37-5", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "37-6", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "37-7", name: "thyme", amount: 2, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Brown chicken", "Add wine and vegetables", "Braise until tender"],
    nutrition: { calories: 480, protein: 38, carbs: 18, fat: 24 },
    cost: 14.0,
  },
  {
    id: "38",
    name: "Beef Bourguignon",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    image: "/beef-bourguignon.jpg",
    ingredients: [
      { id: "38-1", name: "beef chuck", amount: 2, unit: "lb", category: "meat" },
      { id: "38-2", name: "red wine", amount: 3, unit: "cup", category: "pantry" },
      { id: "38-3", name: "bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "38-4", name: "pearl onions", amount: 2, unit: "cup", category: "produce" },
      { id: "38-5", name: "mushrooms", amount: 2, unit: "cup", category: "produce" },
      { id: "38-6", name: "carrots", amount: 3, unit: "whole", category: "produce" },
      { id: "38-7", name: "tomato paste", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Brown beef", "Add wine and vegetables", "Slow cook until tender"],
    nutrition: { calories: 520, protein: 42, carbs: 22, fat: 28 },
    cost: 18.0,
  },
  {
    id: "39",
    name: "Ratatouille",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    image: "/ratatouille.jpg",
    ingredients: [
      { id: "39-1", name: "eggplant", amount: 1, unit: "whole", category: "produce" },
      { id: "39-2", name: "zucchini", amount: 2, unit: "whole", category: "produce" },
      { id: "39-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "39-4", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "39-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "39-6", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "39-7", name: "herbs de provence", amount: 2, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Slice vegetables", "Layer in dish", "Bake until tender"],
    nutrition: { calories: 180, protein: 6, carbs: 32, fat: 6 },
    cost: 8.0,
  },
  {
    id: "40",
    name: "Bouillabaisse",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    image: "/bouillabaisse.jpg",
    ingredients: [
      { id: "40-1", name: "mixed fish", amount: 2, unit: "lb", category: "meat" },
      { id: "40-2", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "40-3", name: "mussels", amount: 1, unit: "lb", category: "meat" },
      { id: "40-4", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "40-5", name: "fennel", amount: 1, unit: "bulb", category: "produce" },
      { id: "40-6", name: "saffron", amount: 1, unit: "tsp", category: "pantry" },
      { id: "40-7", name: "white wine", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Prepare broth", "Add seafood", "Simmer until cooked"],
    nutrition: { calories: 380, protein: 42, carbs: 18, fat: 14 },
    cost: 22.0,
  },
  {
    id: "41",
    name: "Croque Monsieur",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    image: "/croque-monsieur.jpg",
    ingredients: [
      { id: "41-1", name: "bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "41-2", name: "ham", amount: 4, unit: "slice", category: "meat" },
      { id: "41-3", name: "gruyere cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "41-4", name: "butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "41-5", name: "bechamel sauce", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Assemble sandwich", "Top with bechamel", "Bake until golden"],
    nutrition: { calories: 520, protein: 28, carbs: 38, fat: 28 },
    cost: 8.5,
  },
  {
    id: "42",
    name: "Nicoise Salad",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    image: "/nicoise-salad.jpg",
    ingredients: [
      { id: "42-1", name: "tuna", amount: 1, unit: "lb", category: "meat" },
      { id: "42-2", name: "green beans", amount: 2, unit: "cup", category: "produce" },
      { id: "42-3", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "42-4", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "42-5", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "42-6", name: "olives", amount: 1, unit: "cup", category: "pantry" },
      { id: "42-7", name: "vinaigrette", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Cook vegetables and eggs", "Arrange on plate", "Dress with vinaigrette"],
    nutrition: { calories: 420, protein: 32, carbs: 28, fat: 22 },
    cost: 12.0,
  },
  {
    id: "43",
    name: "French Onion Soup",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 60,
    servings: 4,
    image: "/french-onion-soup.jpg",
    ingredients: [
      { id: "43-1", name: "onions", amount: 6, unit: "whole", category: "produce" },
      { id: "43-2", name: "beef broth", amount: 6, unit: "cup", category: "pantry" },
      { id: "43-3", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "43-4", name: "bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "43-5", name: "gruyere cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "43-6", name: "white wine", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Caramelize onions", "Add broth and wine", "Top with bread and cheese"],
    nutrition: { calories: 380, protein: 18, carbs: 42, fat: 16 },
    cost: 9.0,
  },
  {
    id: "44",
    name: "Cassoulet",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 120,
    servings: 8,
    image: "/cassoulet.jpg",
    ingredients: [
      { id: "44-1", name: "white beans", amount: 2, unit: "lb", category: "pantry" },
      { id: "44-2", name: "duck confit", amount: 4, unit: "leg", category: "meat" },
      { id: "44-3", name: "sausage", amount: 1, unit: "lb", category: "meat" },
      { id: "44-4", name: "pork shoulder", amount: 1, unit: "lb", category: "meat" },
      { id: "44-5", name: "tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "44-6", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "44-7", name: "breadcrumbs", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Cook beans", "Layer with meats", "Bake until golden"],
    nutrition: { calories: 680, protein: 48, carbs: 52, fat: 32 },
    cost: 20.0,
  },
  {
    id: "45",
    name: "Moules Mariniere",
    category: "dinner",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/moules-mariniere.jpg",
    ingredients: [
      { id: "45-1", name: "mussels", amount: 3, unit: "lb", category: "meat" },
      { id: "45-2", name: "white wine", amount: 2, unit: "cup", category: "pantry" },
      { id: "45-3", name: "shallots", amount: 3, unit: "whole", category: "produce" },
      { id: "45-4", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "45-5", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "45-6", name: "parsley", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Clean mussels", "Steam with wine", "Serve with broth"],
    nutrition: { calories: 320, protein: 28, carbs: 12, fat: 14 },
    cost: 16.0,
  },
  {
    id: "46",
    name: "Tarte Tatin",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    image: "/tarte-tatin.jpg",
    ingredients: [
      { id: "46-1", name: "apples", amount: 6, unit: "whole", category: "produce" },
      { id: "46-2", name: "puff pastry", amount: 1, unit: "sheet", category: "pantry" },
      { id: "46-3", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "46-4", name: "sugar", amount: 1, unit: "cup", category: "pantry" },
      { id: "46-5", name: "vanilla", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Caramelize apples", "Top with pastry", "Bake and flip"],
    nutrition: { calories: 380, protein: 4, carbs: 58, fat: 16 },
    cost: 7.0,
  },
  {
    id: "47",
    name: "Paella",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    image: "/paella.jpg",
    ingredients: [
      { id: "47-1", name: "rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "47-2", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "47-3", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "47-4", name: "mussels", amount: 1, unit: "lb", category: "meat" },
      { id: "47-5", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "47-6", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "47-7", name: "saffron", amount: 1, unit: "tsp", category: "pantry" },
      { id: "47-8", name: "peas", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Sauté meats", "Add rice and broth", "Cook until rice is done"],
    nutrition: { calories: 520, protein: 38, carbs: 52, fat: 18 },
    cost: 18.0,
  },
  {
    id: "48",
    name: "Gazpacho",
    category: "lunch",
    diet: "vegan",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    image: "/gazpacho.jpg",
    ingredients: [
      { id: "48-1", name: "tomatoes", amount: 6, unit: "whole", category: "produce" },
      { id: "48-2", name: "cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "48-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "48-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "48-5", name: "garlic", amount: 2, unit: "clove", category: "produce" },
      { id: "48-6", name: "olive oil", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "48-7", name: "vinegar", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Blend all ingredients", "Chill", "Serve cold"],
    nutrition: { calories: 180, protein: 4, carbs: 28, fat: 8 },
    cost: 6.0,
  },
  {
    id: "49",
    name: "Schnitzel",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    image: "/schnitzel.jpg",
    ingredients: [
      { id: "49-1", name: "pork cutlets", amount: 4, unit: "piece", category: "meat" },
      { id: "49-2", name: "flour", amount: 1, unit: "cup", category: "pantry" },
      { id: "49-3", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "49-4", name: "breadcrumbs", amount: 2, unit: "cup", category: "pantry" },
      { id: "49-5", name: "lemon", amount: 2, unit: "whole", category: "produce" },
      { id: "49-6", name: "oil", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Bread cutlets", "Fry until golden", "Serve with lemon"],
    nutrition: { calories: 480, protein: 32, carbs: 38, fat: 22 },
    cost: 10.0,
  },
  {
    id: "50",
    name: "Goulash",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    image: "/goulash.jpg",
    ingredients: [
      { id: "50-1", name: "beef chuck", amount: 2, unit: "lb", category: "meat" },
      { id: "50-2", name: "onions", amount: 3, unit: "whole", category: "produce" },
      { id: "50-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "50-4", name: "tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "50-5", name: "paprika", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "50-6", name: "caraway seeds", amount: 1, unit: "tsp", category: "pantry" },
      { id: "50-7", name: "beef broth", amount: 4, unit: "cup", category: "pantry" },
    ],
    instructions: ["Brown beef", "Add vegetables and spices", "Simmer until tender"],
    nutrition: { calories: 420, protein: 38, carbs: 22, fat: 20 },
    cost: 14.0,
  },
  {
    id: "51",
    name: "Pierogi",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    image: "/pierogi.jpg",
    ingredients: [
      { id: "51-1", name: "flour", amount: 3, unit: "cup", category: "pantry" },
      { id: "51-2", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "51-3", name: "cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "51-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "51-5", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "51-6", name: "sour cream", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Make dough", "Prepare filling", "Boil and fry"],
    nutrition: { calories: 420, protein: 14, carbs: 58, fat: 16 },
    cost: 8.0,
  },
  {
    id: "52",
    name: "Sauerbraten",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 120,
    servings: 6,
    image: "/sauerbraten.jpg",
    ingredients: [
      { id: "52-1", name: "beef roast", amount: 3, unit: "lb", category: "meat" },
      { id: "52-2", name: "red wine vinegar", amount: 2, unit: "cup", category: "pantry" },
      { id: "52-3", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "52-4", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "52-5", name: "gingersnaps", amount: 1, unit: "cup", category: "pantry" },
      { id: "52-6", name: "bay leaves", amount: 3, unit: "whole", category: "pantry" },
    ],
    instructions: ["Marinate beef", "Braise until tender", "Thicken sauce"],
    nutrition: { calories: 520, protein: 45, carbs: 28, fat: 24 },
    cost: 16.0,
  },
  {
    id: "53",
    name: "Risotto",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    image: "/risotto.jpg",
    ingredients: [
      { id: "53-1", name: "arborio rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "53-2", name: "white wine", amount: 1, unit: "cup", category: "pantry" },
      { id: "53-3", name: "parmesan cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "53-4", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "53-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "53-6", name: "chicken broth", amount: 6, unit: "cup", category: "pantry" },
    ],
    instructions: ["Toast rice", "Add broth gradually", "Finish with cheese"],
    nutrition: { calories: 420, protein: 14, carbs: 58, fat: 14 },
    cost: 9.0,
  },
  {
    id: "54",
    name: "Osso Buco",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    image: "/osso-buco.jpg",
    ingredients: [
      { id: "54-1", name: "veal shanks", amount: 4, unit: "piece", category: "meat" },
      { id: "54-2", name: "white wine", amount: 2, unit: "cup", category: "pantry" },
      { id: "54-3", name: "tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "54-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "54-5", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "54-6", name: "celery", amount: 2, unit: "stalk", category: "produce" },
      { id: "54-7", name: "gremolata", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Brown shanks", "Braise with vegetables", "Serve with gremolata"],
    nutrition: { calories: 480, protein: 42, carbs: 18, fat: 24 },
    cost: 20.0,
  },
  {
    id: "55",
    name: "Polenta",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    image: "/polenta.jpg",
    ingredients: [
      { id: "55-1", name: "cornmeal", amount: 2, unit: "cup", category: "pantry" },
      { id: "55-2", name: "water", amount: 6, unit: "cup", category: "pantry" },
      { id: "55-3", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "55-4", name: "parmesan cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "55-5", name: "salt", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Boil water", "Whisk in cornmeal", "Stir until thick"],
    nutrition: { calories: 320, protein: 10, carbs: 48, fat: 12 },
    cost: 5.0,
  },
  {
    id: "56",
    name: "Tiramisu",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    image: "/tiramisu.jpg",
    ingredients: [
      { id: "56-1", name: "ladyfingers", amount: 24, unit: "piece", category: "pantry" },
      { id: "56-2", name: "mascarpone", amount: 2, unit: "cup", category: "dairy" },
      { id: "56-3", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "56-4", name: "sugar", amount: 1, unit: "cup", category: "pantry" },
      { id: "56-5", name: "espresso", amount: 2, unit: "cup", category: "pantry" },
      { id: "56-6", name: "cocoa powder", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Make cream", "Dip ladyfingers", "Layer and chill"],
    nutrition: { calories: 380, protein: 8, carbs: 42, fat: 20 },
    cost: 10.0,
  },
  {
    id: "57",
    name: "Kung Pao Chicken",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    image: "/kung-pao-chicken.jpg",
    ingredients: [
      { id: "57-1", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "57-2", name: "peanuts", amount: 1, unit: "cup", category: "pantry" },
      { id: "57-3", name: "dried chilies", amount: 6, unit: "whole", category: "pantry" },
      { id: "57-4", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "57-5", name: "soy sauce", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "57-6", name: "rice vinegar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "57-7", name: "ginger", amount: 1, unit: "inch", category: "produce" },
    ],
    instructions: ["Stir-fry chicken", "Add vegetables", "Toss with sauce"],
    nutrition: { calories: 420, protein: 32, carbs: 22, fat: 24 },
    cost: 10.0,
  },
  {
    id: "58",
    name: "Mapo Tofu",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/mapo-tofu.jpg",
    ingredients: [
      { id: "58-1", name: "tofu", amount: 1, unit: "lb", category: "produce" },
      { id: "58-2", name: "ground pork", amount: 1, unit: "lb", category: "meat" },
      { id: "58-3", name: "doubanjiang", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "58-4", name: "sichuan peppercorns", amount: 1, unit: "tsp", category: "pantry" },
      { id: "58-5", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "58-6", name: "ginger", amount: 1, unit: "inch", category: "produce" },
      { id: "58-7", name: "green onions", amount: 3, unit: "stalk", category: "produce" },
    ],
    instructions: ["Cook pork", "Add tofu and sauce", "Simmer until done"],
    nutrition: { calories: 380, protein: 28, carbs: 12, fat: 26 },
    cost: 8.0,
  },
  {
    id: "59",
    name: "Dumplings",
    category: "lunch",
    diet: "classic",
    prepTime: 40,
    cookTime: 15,
    servings: 4,
    image: "/dumplings.jpg",
    ingredients: [
      { id: "59-1", name: "dumpling wrappers", amount: 40, unit: "piece", category: "pantry" },
      { id: "59-2", name: "ground pork", amount: 1, unit: "lb", category: "meat" },
      { id: "59-3", name: "cabbage", amount: 2, unit: "cup", category: "produce" },
      { id: "59-4", name: "ginger", amount: 1, unit: "inch", category: "produce" },
      { id: "59-5", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "59-6", name: "soy sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "59-7", name: "sesame oil", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Make filling", "Wrap dumplings", "Steam or pan-fry"],
    nutrition: { calories: 380, protein: 22, carbs: 42, fat: 14 },
    cost: 9.0,
  },
  {
    id: "60",
    name: "Pho",
    category: "lunch",
    diet: "classic",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    image: "/pho.jpg",
    ingredients: [
      { id: "60-1", name: "rice noodles", amount: 1, unit: "lb", category: "pantry" },
      { id: "60-2", name: "beef", amount: 1, unit: "lb", category: "meat" },
      { id: "60-3", name: "beef broth", amount: 8, unit: "cup", category: "pantry" },
      { id: "60-4", name: "star anise", amount: 3, unit: "whole", category: "pantry" },
      { id: "60-5", name: "cinnamon", amount: 1, unit: "stick", category: "pantry" },
      { id: "60-6", name: "ginger", amount: 2, unit: "inch", category: "produce" },
      { id: "60-7", name: "bean sprouts", amount: 2, unit: "cup", category: "produce" },
      { id: "60-8", name: "basil", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Prepare broth", "Cook noodles", "Assemble with toppings"],
    nutrition: { calories: 420, protein: 28, carbs: 52, fat: 12 },
    cost: 11.0,
  },
  {
    id: "61",
    name: "Bibimbap",
    category: "lunch",
    diet: "classic",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    image: "/bibimbap.jpg",
    ingredients: [
      { id: "61-1", name: "rice", amount: 3, unit: "cup", category: "pantry" },
      { id: "61-2", name: "beef", amount: 1, unit: "lb", category: "meat" },
      { id: "61-3", name: "spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "61-4", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "61-5", name: "mushrooms", amount: 2, unit: "cup", category: "produce" },
      { id: "61-6", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "61-7", name: "gochujang", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Prepare vegetables", "Cook beef", "Assemble in bowl"],
    nutrition: { calories: 520, protein: 32, carbs: 62, fat: 16 },
    cost: 12.0,
  },
  {
    id: "62",
    name: "Bulgogi",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    image: "/bulgogi.jpg",
    ingredients: [
      { id: "62-1", name: "beef", amount: 1, unit: "lb", category: "meat" },
      { id: "62-2", name: "soy sauce", amount: 4, unit: "tbsp", category: "pantry" },
      { id: "62-3", name: "sugar", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "62-4", name: "sesame oil", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "62-5", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "62-6", name: "pear", amount: 1, unit: "whole", category: "produce" },
      { id: "62-7", name: "green onions", amount: 3, unit: "stalk", category: "produce" },
    ],
    instructions: ["Marinate beef", "Grill or stir-fry", "Serve with rice"],
    nutrition: { calories: 380, protein: 32, carbs: 18, fat: 20 },
    cost: 11.0,
  },
  {
    id: "63",
    name: "Banh Mi",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    image: "/banh-mi.jpg",
    ingredients: [
      { id: "63-1", name: "baguette", amount: 2, unit: "whole", category: "pantry" },
      { id: "63-2", name: "pork", amount: 1, unit: "lb", category: "meat" },
      { id: "63-3", name: "pickled vegetables", amount: 1, unit: "cup", category: "produce" },
      { id: "63-4", name: "cilantro", amount: 1, unit: "cup", category: "produce" },
      { id: "63-5", name: "cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "63-6", name: "mayonnaise", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "63-7", name: "jalapeños", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Grill pork", "Prepare vegetables", "Assemble sandwich"],
    nutrition: { calories: 480, protein: 28, carbs: 52, fat: 18 },
    cost: 9.0,
  },
  {
    id: "64",
    name: "Spring Rolls",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    image: "/spring-rolls.jpg",
    ingredients: [
      { id: "64-1", name: "rice paper", amount: 12, unit: "sheet", category: "pantry" },
      { id: "64-2", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "64-3", name: "rice noodles", amount: 4, unit: "oz", category: "pantry" },
      { id: "64-4", name: "lettuce", amount: 1, unit: "head", category: "produce" },
      { id: "64-5", name: "mint", amount: 1, unit: "cup", category: "produce" },
      { id: "64-6", name: "peanut sauce", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Prepare fillings", "Soak rice paper", "Roll and serve"],
    nutrition: { calories: 280, protein: 22, carbs: 32, fat: 8 },
    cost: 10.0,
  },
  {
    id: "65",
    name: "Katsu Curry",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    image: "/katsu-curry.jpg",
    ingredients: [
      { id: "65-1", name: "pork cutlets", amount: 4, unit: "piece", category: "meat" },
      { id: "65-2", name: "curry roux", amount: 1, unit: "box", category: "pantry" },
      { id: "65-3", name: "potatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "65-4", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "65-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "65-6", name: "panko", amount: 2, unit: "cup", category: "pantry" },
      { id: "65-7", name: "rice", amount: 3, unit: "cup", category: "pantry" },
    ],
    instructions: ["Bread and fry cutlets", "Make curry", "Serve over rice"],
    nutrition: { calories: 620, protein: 32, carbs: 72, fat: 22 },
    cost: 12.0,
  },
  {
    id: "66",
    name: "Jollof Rice",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    image: "/jollof-rice.jpg",
    ingredients: [
      { id: "66-1", name: "rice", amount: 3, unit: "cup", category: "pantry" },
      { id: "66-2", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "66-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "66-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "66-5", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "66-6", name: "tomato paste", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "66-7", name: "curry powder", amount: 2, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Blend tomatoes and peppers", "Cook rice in sauce", "Add chicken"],
    nutrition: { calories: 480, protein: 24, carbs: 68, fat: 12 },
    cost: 10.0,
  },
  {
    id: "67",
    name: "Suya",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    image: "/suya.jpg",
    ingredients: [
      { id: "67-1", name: "beef", amount: 1, unit: "lb", category: "meat" },
      { id: "67-2", name: "peanuts", amount: 1, unit: "cup", category: "pantry" },
      { id: "67-3", name: "cayenne pepper", amount: 2, unit: "tsp", category: "pantry" },
      { id: "67-4", name: "ginger", amount: 1, unit: "inch", category: "produce" },
      { id: "67-5", name: "garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "67-6", name: "onions", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Make spice blend", "Marinate beef", "Grill on skewers"],
    nutrition: { calories: 380, protein: 32, carbs: 12, fat: 24 },
    cost: 9.0,
  },
  {
    id: "68",
    name: "Bobotie",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    image: "/bobotie.jpg",
    ingredients: [
      { id: "68-1", name: "ground beef", amount: 2, unit: "lb", category: "meat" },
      { id: "68-2", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "68-3", name: "curry powder", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "68-4", name: "raisins", amount: 1, unit: "cup", category: "pantry" },
      { id: "68-5", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "68-6", name: "milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "68-7", name: "bread", amount: 2, unit: "slice", category: "pantry" },
    ],
    instructions: ["Cook meat mixture", "Top with custard", "Bake until set"],
    nutrition: { calories: 480, protein: 32, carbs: 38, fat: 22 },
    cost: 11.0,
  },
  {
    id: "69",
    name: "Bunny Chow",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    image: "/bunny-chow.jpg",
    ingredients: [
      { id: "69-1", name: "bread loaf", amount: 1, unit: "whole", category: "pantry" },
      { id: "69-2", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "69-3", name: "curry powder", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "69-4", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "69-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "69-6", name: "potatoes", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Make curry", "Hollow bread", "Fill with curry"],
    nutrition: { calories: 520, protein: 28, carbs: 62, fat: 18 },
    cost: 8.0,
  },
  {
    id: "70",
    name: "Peri Peri Chicken",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    image: "/peri-peri-chicken.jpg",
    ingredients: [
      { id: "70-1", name: "chicken", amount: 1, unit: "whole", category: "meat" },
      { id: "70-2", name: "peri peri peppers", amount: 6, unit: "whole", category: "produce" },
      { id: "70-3", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "70-4", name: "lemon", amount: 2, unit: "whole", category: "produce" },
      { id: "70-5", name: "paprika", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "70-6", name: "olive oil", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Make peri peri sauce", "Marinate chicken", "Grill until done"],
    nutrition: { calories: 420, protein: 38, carbs: 8, fat: 26 },
    cost: 10.0,
  },
  {
    id: "71",
    name: "Fufu and Egusi",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 45,
    servings: 4,
    image: "/fufu-egusi.jpg",
    ingredients: [
      { id: "71-1", name: "cassava flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "71-2", name: "egusi seeds", amount: 1, unit: "cup", category: "pantry" },
      { id: "71-3", name: "spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "71-4", name: "beef", amount: 1, unit: "lb", category: "meat" },
      { id: "71-5", name: "palm oil", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "71-6", name: "onions", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Make fufu", "Prepare egusi soup", "Serve together"],
    nutrition: { calories: 520, protein: 28, carbs: 52, fat: 24 },
    cost: 12.0,
  },
  {
    id: "72",
    name: "Injera with Doro Wat",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 60,
    servings: 6,
    image: "/injera-doro-wat.jpg",
    ingredients: [
      { id: "72-1", name: "teff flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "72-2", name: "chicken", amount: 1, unit: "whole", category: "meat" },
      { id: "72-3", name: "berbere spice", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "72-4", name: "onions", amount: 3, unit: "whole", category: "produce" },
      { id: "72-5", name: "eggs", amount: 6, unit: "whole", category: "meat" },
      { id: "72-6", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Make injera", "Prepare doro wat", "Serve together"],
    nutrition: { calories: 580, protein: 38, carbs: 52, fat: 24 },
    cost: 14.0,
  },
  {
    id: "73",
    name: "Chakalaka",
    category: "lunch",
    diet: "vegan",
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    image: "/chakalaka.jpg",
    ingredients: [
      { id: "73-1", name: "beans", amount: 2, unit: "cup", category: "pantry" },
      { id: "73-2", name: "bell peppers", amount: 3, unit: "whole", category: "produce" },
      { id: "73-3", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "73-4", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "73-5", name: "curry powder", amount: 2, unit: "tsp", category: "pantry" },
      { id: "73-6", name: "onions", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Sauté vegetables", "Add beans and spices", "Simmer until done"],
    nutrition: { calories: 220, protein: 12, carbs: 38, fat: 4 },
    cost: 6.0,
  },
  {
    id: "74",
    name: "Carbonara",
    category: "dinner",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/carbonara.jpg",
    ingredients: [
      { id: "74-1", name: "spaghetti", amount: 1, unit: "lb", category: "pantry" },
      { id: "74-2", name: "pancetta", amount: 6, unit: "oz", category: "meat" },
      { id: "74-3", name: "eggs", amount: 4, unit: "whole", category: "meat" },
      { id: "74-4", name: "parmesan cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "74-5", name: "black pepper", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Cook pasta", "Fry pancetta", "Toss with egg mixture"],
    nutrition: { calories: 520, protein: 24, carbs: 58, fat: 22 },
    cost: 9.0,
  },
  {
    id: "75",
    name: "Lasagna",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    image: "/lasagna.jpg",
    ingredients: [
      { id: "75-1", name: "lasagna noodles", amount: 1, unit: "lb", category: "pantry" },
      { id: "75-2", name: "ground beef", amount: 1, unit: "lb", category: "meat" },
      { id: "75-3", name: "ricotta cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "75-4", name: "mozzarella cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "75-5", name: "marinara sauce", amount: 4, unit: "cup", category: "pantry" },
      { id: "75-6", name: "parmesan cheese", amount: 1, unit: "cup", category: "dairy" },
    ],
    instructions: ["Layer noodles and filling", "Top with cheese", "Bake until bubbly"],
    nutrition: { calories: 580, protein: 32, carbs: 48, fat: 28 },
    cost: 14.0,
  },
  {
    id: "76",
    name: "Margherita Pizza",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    image: "/margherita-pizza.jpg",
    ingredients: [
      { id: "76-1", name: "pizza dough", amount: 1, unit: "lb", category: "pantry" },
      { id: "76-2", name: "tomato sauce", amount: 1, unit: "cup", category: "pantry" },
      { id: "76-3", name: "mozzarella cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "76-4", name: "basil", amount: 1, unit: "cup", category: "produce" },
      { id: "76-5", name: "olive oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Stretch dough", "Add toppings", "Bake until crispy"],
    nutrition: { calories: 420, protein: 18, carbs: 52, fat: 16 },
    cost: 8.0,
  },
  {
    id: "77",
    name: "Chicken Parmesan",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    image: "/chicken-parmesan.jpg",
    ingredients: [
      { id: "77-1", name: "chicken breast", amount: 4, unit: "piece", category: "meat" },
      { id: "77-2", name: "breadcrumbs", amount: 2, unit: "cup", category: "pantry" },
      { id: "77-3", name: "marinara sauce", amount: 2, unit: "cup", category: "pantry" },
      { id: "77-4", name: "mozzarella cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "77-5", name: "parmesan cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "77-6", name: "eggs", amount: 2, unit: "whole", category: "meat" },
    ],
    instructions: ["Bread chicken", "Fry until golden", "Top with sauce and cheese"],
    nutrition: { calories: 580, protein: 42, carbs: 38, fat: 28 },
    cost: 12.0,
  },
  {
    id: "78",
    name: "Fettuccine Alfredo",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/fettuccine-alfredo.jpg",
    ingredients: [
      { id: "78-1", name: "fettuccine", amount: 1, unit: "lb", category: "pantry" },
      { id: "78-2", name: "butter", amount: 1, unit: "cup", category: "dairy" },
      { id: "78-3", name: "heavy cream", amount: 2, unit: "cup", category: "dairy" },
      { id: "78-4", name: "parmesan cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "78-5", name: "garlic", amount: 3, unit: "clove", category: "produce" },
    ],
    instructions: ["Cook pasta", "Make alfredo sauce", "Toss together"],
    nutrition: { calories: 680, protein: 22, carbs: 58, fat: 42 },
    cost: 10.0,
  },
  {
    id: "79",
    name: "Minestrone Soup",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    image: "/minestrone-soup.jpg",
    ingredients: [
      { id: "79-1", name: "pasta", amount: 1, unit: "cup", category: "pantry" },
      { id: "79-2", name: "beans", amount: 2, unit: "cup", category: "pantry" },
      { id: "79-3", name: "tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "79-4", name: "zucchini", amount: 2, unit: "whole", category: "produce" },
      { id: "79-5", name: "carrots", amount: 2, unit: "whole", category: "produce" },
      { id: "79-6", name: "celery", amount: 2, unit: "stalk", category: "produce" },
      { id: "79-7", name: "vegetable broth", amount: 6, unit: "cup", category: "pantry" },
    ],
    instructions: ["Sauté vegetables", "Add broth and beans", "Simmer with pasta"],
    nutrition: { calories: 280, protein: 12, carbs: 48, fat: 6 },
    cost: 7.0,
  },
  {
    id: "80",
    name: "Caprese Salad",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    image: "/caprese-salad.jpg",
    ingredients: [
      { id: "80-1", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "80-2", name: "mozzarella cheese", amount: 1, unit: "lb", category: "dairy" },
      { id: "80-3", name: "basil", amount: 1, unit: "cup", category: "produce" },
      { id: "80-4", name: "olive oil", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "80-5", name: "balsamic vinegar", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Slice tomatoes and mozzarella", "Layer with basil", "Drizzle with oil"],
    nutrition: { calories: 320, protein: 18, carbs: 12, fat: 24 },
    cost: 9.0,
  },
  {
    id: "81",
    name: "Penne Arrabbiata",
    category: "dinner",
    diet: "vegan",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    image: "/penne-arrabbiata.jpg",
    ingredients: [
      { id: "81-1", name: "penne pasta", amount: 1, unit: "lb", category: "pantry" },
      { id: "81-2", name: "tomatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "81-3", name: "red pepper flakes", amount: 2, unit: "tsp", category: "pantry" },
      { id: "81-4", name: "garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "81-5", name: "olive oil", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "81-6", name: "parsley", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook pasta", "Make spicy tomato sauce", "Toss together"],
    nutrition: { calories: 420, protein: 14, carbs: 72, fat: 10 },
    cost: 7.0,
  },
  {
    id: "82",
    name: "BBQ Ribs",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 120,
    servings: 4,
    image: "/bbq-ribs.jpg",
    ingredients: [
      { id: "82-1", name: "pork ribs", amount: 3, unit: "lb", category: "meat" },
      { id: "82-2", name: "bbq sauce", amount: 2, unit: "cup", category: "pantry" },
      { id: "82-3", name: "brown sugar", amount: 1, unit: "cup", category: "pantry" },
      { id: "82-4", name: "paprika", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "82-5", name: "garlic powder", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "82-6", name: "onion powder", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Rub ribs with spices", "Slow cook", "Glaze with sauce"],
    nutrition: { calories: 680, protein: 42, carbs: 48, fat: 38 },
    cost: 16.0,
  },
  {
    id: "83",
    name: "Mac and Cheese",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    image: "/mac-and-cheese.jpg",
    ingredients: [
      { id: "83-1", name: "macaroni", amount: 1, unit: "lb", category: "pantry" },
      { id: "83-2", name: "cheddar cheese", amount: 3, unit: "cup", category: "dairy" },
      { id: "83-3", name: "milk", amount: 2, unit: "cup", category: "dairy" },
      { id: "83-4", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "83-5", name: "flour", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "83-6", name: "breadcrumbs", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Cook pasta", "Make cheese sauce", "Bake with topping"],
    nutrition: { calories: 520, protein: 22, carbs: 58, fat: 24 },
    cost: 8.0,
  },
  {
    id: "84",
    name: "Pulled Pork",
    category: "dinner",
    diet: "classic",
    prepTime: 30,
    cookTime: 240,
    servings: 8,
    image: "/pulled-pork.jpg",
    ingredients: [
      { id: "84-1", name: "pork shoulder", amount: 4, unit: "lb", category: "meat" },
      { id: "84-2", name: "bbq sauce", amount: 2, unit: "cup", category: "pantry" },
      { id: "84-3", name: "buns", amount: 8, unit: "whole", category: "pantry" },
      { id: "84-4", name: "coleslaw", amount: 2, unit: "cup", category: "produce" },
      { id: "84-5", name: "dry rub", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Rub pork", "Slow cook until tender", "Shred and serve"],
    nutrition: { calories: 580, protein: 38, carbs: 42, fat: 28 },
    cost: 14.0,
  },
  {
    id: "85",
    name: "Chicken Wings",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    image: "/chicken-wings.jpg",
    ingredients: [
      { id: "85-1", name: "chicken wings", amount: 2, unit: "lb", category: "meat" },
      { id: "85-2", name: "buffalo sauce", amount: 1, unit: "cup", category: "pantry" },
      { id: "85-3", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "85-4", name: "ranch dressing", amount: 1, unit: "cup", category: "dairy" },
      { id: "85-5", name: "celery", amount: 4, unit: "stalk", category: "produce" },
    ],
    instructions: ["Bake wings", "Toss in sauce", "Serve with ranch"],
    nutrition: { calories: 520, protein: 32, carbs: 8, fat: 42 },
    cost: 10.0,
  },
  {
    id: "86",
    name: "Philly Cheesesteak",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    image: "/philly-cheesesteak.jpg",
    ingredients: [
      { id: "86-1", name: "ribeye steak", amount: 1, unit: "lb", category: "meat" },
      { id: "86-2", name: "hoagie rolls", amount: 4, unit: "whole", category: "pantry" },
      { id: "86-3", name: "provolone cheese", amount: 8, unit: "slice", category: "dairy" },
      { id: "86-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "86-5", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Sauté steak and vegetables", "Melt cheese", "Assemble sandwich"],
    nutrition: { calories: 620, protein: 38, carbs: 48, fat: 32 },
    cost: 14.0,
  },
  {
    id: "87",
    name: "Clam Chowder",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    image: "/clam-chowder.jpg",
    ingredients: [
      { id: "87-1", name: "clams", amount: 2, unit: "lb", category: "meat" },
      { id: "87-2", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "87-3", name: "bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "87-4", name: "cream", amount: 2, unit: "cup", category: "dairy" },
      { id: "87-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "87-6", name: "celery", amount: 2, unit: "stalk", category: "produce" },
    ],
    instructions: ["Cook bacon", "Add vegetables", "Simmer with clams and cream"],
    nutrition: { calories: 420, protein: 22, carbs: 32, fat: 24 },
    cost: 12.0,
  },
  {
    id: "88",
    name: "Jambalaya",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    image: "/jambalaya.jpg",
    ingredients: [
      { id: "88-1", name: "rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "88-2", name: "chicken", amount: 1, unit: "lb", category: "meat" },
      { id: "88-3", name: "sausage", amount: 1, unit: "lb", category: "meat" },
      { id: "88-4", name: "shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "88-5", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "88-6", name: "celery", amount: 2, unit: "stalk", category: "produce" },
      { id: "88-7", name: "cajun seasoning", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Brown meats", "Add vegetables and rice", "Simmer until done"],
    nutrition: { calories: 580, protein: 42, carbs: 52, fat: 22 },
    cost: 16.0,
  },
  {
    id: "89",
    name: "Meatloaf",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 60,
    servings: 6,
    image: "/meatloaf.jpg",
    ingredients: [
      { id: "89-1", name: "ground beef", amount: 2, unit: "lb", category: "meat" },
      { id: "89-2", name: "breadcrumbs", amount: 1, unit: "cup", category: "pantry" },
      { id: "89-3", name: "eggs", amount: 2, unit: "whole", category: "meat" },
      { id: "89-4", name: "ketchup", amount: 1, unit: "cup", category: "pantry" },
      { id: "89-5", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "89-6", name: "worcestershire sauce", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Mix ingredients", "Shape into loaf", "Bake with glaze"],
    nutrition: { calories: 480, protein: 32, carbs: 28, fat: 26 },
    cost: 10.0,
  },
  {
    id: "90",
    name: "Aloo Gobi",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    image: "/aloo-gobi-cauliflower.jpg",
    ingredients: [
      { id: "90-1", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "90-2", name: "cauliflower", amount: 1, unit: "head", category: "produce" },
      { id: "90-3", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "90-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "90-5", name: "turmeric", amount: 1, unit: "tsp", category: "pantry" },
      { id: "90-6", name: "cumin", amount: 1, unit: "tsp", category: "pantry" },
      { id: "90-7", name: "garam masala", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Sauté spices", "Add vegetables", "Cook until tender"],
    nutrition: { calories: 220, protein: 6, carbs: 42, fat: 6 },
    cost: 5.0,
  },
  {
    id: "91",
    name: "Tandoori Chicken",
    category: "dinner",
    diet: "classic",
    prepTime: 60,
    cookTime: 30,
    servings: 4,
    image: "/tandoori-chicken-grilled.jpg",
    ingredients: [
      { id: "91-1", name: "chicken", amount: 1, unit: "whole", category: "meat" },
      { id: "91-2", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "91-3", name: "tandoori masala", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "91-4", name: "lemon juice", amount: 2, unit: "tbsp", category: "produce" },
      { id: "91-5", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "91-6", name: "oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Marinate chicken", "Grill or bake", "Serve with naan"],
    nutrition: { calories: 420, protein: 38, carbs: 12, fat: 26 },
    cost: 10.0,
  },
  {
    id: "92",
    name: "Samosas",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    image: "/samosa-fried-pastry.jpg",
    ingredients: [
      { id: "92-1", name: "flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "92-2", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "92-3", name: "peas", amount: 1, unit: "cup", category: "produce" },
      { id: "92-4", name: "cumin", amount: 1, unit: "tsp", category: "pantry" },
      { id: "92-5", name: "coriander", amount: 1, unit: "tsp", category: "pantry" },
      { id: "92-6", name: "oil", amount: 2, unit: "cup", category: "pantry" },
    ],
    instructions: ["Make dough", "Prepare filling", "Fry until golden"],
    nutrition: { calories: 320, protein: 8, carbs: 48, fat: 12 },
    cost: 5.0,
  },
  {
    id: "93",
    name: "Rogan Josh",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    image: "/rogan-josh.jpg",
    ingredients: [
      { id: "93-1", name: "lamb", amount: 1, unit: "lb", category: "meat" },
      { id: "93-2", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "93-3", name: "tomatoes", amount: 2, unit: "whole", category: "produce" },
      { id: "93-4", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "93-5", name: "kashmiri chili", amount: 2, unit: "tsp", category: "pantry" },
      { id: "93-6", name: "garam masala", amount: 1, unit: "tsp", category: "pantry" },
      { id: "93-7", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Brown lamb", "Add spices and yogurt", "Simmer until tender"],
    nutrition: { calories: 480, protein: 32, carbs: 18, fat: 32 },
    cost: 14.0,
  },
  {
    id: "94",
    name: "Pav Bhaji",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    image: "/pav-bhaji.jpg",
    ingredients: [
      { id: "94-1", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "94-2", name: "pav buns", amount: 8, unit: "whole", category: "pantry" },
      { id: "94-3", name: "mixed vegetables", amount: 2, unit: "cup", category: "produce" },
      { id: "94-4", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "94-5", name: "pav bhaji masala", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "94-6", name: "butter", amount: 4, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Mash vegetables", "Cook with spices", "Serve with buttered pav"],
    nutrition: { calories: 420, protein: 12, carbs: 62, fat: 16 },
    cost: 6.0,
  },
  {
    id: "95",
    name: "Idli Sambar",
    category: "breakfast",
    diet: "vegan",
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    image: "/idli-sambar.jpg",
    ingredients: [
      { id: "95-1", name: "idli batter", amount: 2, unit: "cup", category: "pantry" },
      { id: "95-2", name: "lentils", amount: 1, unit: "cup", category: "pantry" },
      { id: "95-3", name: "vegetables", amount: 2, unit: "cup", category: "produce" },
      { id: "95-4", name: "tamarind", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "95-5", name: "sambar powder", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "95-6", name: "curry leaves", amount: 10, unit: "whole", category: "produce" },
    ],
    instructions: ["Steam idlis", "Prepare sambar", "Serve together"],
    nutrition: { calories: 280, protein: 12, carbs: 52, fat: 4 },
    cost: 4.0,
  },
  {
    id: "96",
    name: "Paneer Tikka",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    image: "/paneer-tikka-grilled.jpg",
    ingredients: [
      { id: "96-1", name: "paneer", amount: 1, unit: "lb", category: "dairy" },
      { id: "96-2", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "96-3", name: "bell peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "96-4", name: "onions", amount: 1, unit: "whole", category: "produce" },
      { id: "96-5", name: "tikka masala", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "96-6", name: "lemon juice", amount: 2, unit: "tbsp", category: "produce" },
    ],
    instructions: ["Marinate paneer", "Skewer with vegetables", "Grill until charred"],
    nutrition: { calories: 320, protein: 18, carbs: 18, fat: 20 },
    cost: 8.0,
  },
  {
    id: "97",
    name: "Rajma",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    image: "/rajma.jpg",
    ingredients: [
      { id: "97-1", name: "kidney beans", amount: 2, unit: "cup", category: "pantry" },
      { id: "97-2", name: "tomatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "97-3", name: "onions", amount: 2, unit: "whole", category: "produce" },
      { id: "97-4", name: "ginger garlic paste", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "97-5", name: "rajma masala", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "97-6", name: "cream", amount: 2, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Soak and cook beans", "Prepare gravy", "Simmer together"],
    nutrition: { calories: 320, protein: 16, carbs: 52, fat: 6 },
    cost: 5.0,
  },
  {
    id: "98",
    name: "Vada Pav",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    image: "/vada-pav.jpg",
    ingredients: [
      { id: "98-1", name: "potatoes", amount: 4, unit: "whole", category: "produce" },
      { id: "98-2", name: "pav buns", amount: 4, unit: "whole", category: "pantry" },
      { id: "98-3", name: "chickpea flour", amount: 1, unit: "cup", category: "pantry" },
      { id: "98-4", name: "green chilies", amount: 3, unit: "whole", category: "produce" },
      { id: "98-5", name: "garlic chutney", amount: 4, unit: "tbsp", category: "pantry" },
      { id: "98-6", name: "oil", amount: 2, unit: "cup", category: "pantry" },
    ],
    instructions: ["Make potato filling", "Coat in batter", "Fry and serve in pav"],
    nutrition: { calories: 380, protein: 10, carbs: 58, fat: 14 },
    cost: 4.0,
  },
  {
    id: "99",
    name: "Hyderabadi Biryani",
    category: "dinner",
    diet: "classic",
    prepTime: 40,
    cookTime: 60,
    servings: 6,
    image: "/hyderabadi-biryani.jpg",
    ingredients: [
      { id: "99-1", name: "basmati rice", amount: 3, unit: "cup", category: "pantry" },
      { id: "99-2", name: "chicken or mutton", amount: 2, unit: "lb", category: "meat" },
      { id: "99-3", name: "yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "99-4", name: "fried onions", amount: 1, unit: "cup", category: "produce" },
      { id: "99-5", name: "mint", amount: 1, unit: "cup", category: "produce" },
      { id: "99-6", name: "saffron", amount: 1, unit: "tsp", category: "pantry" },
      { id: "99-7", name: "biryani masala", amount: 3, unit: "tbsp", category: "pantry" },
      { id: "99-8", name: "ghee", amount: 4, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Marinate meat", "Layer with rice", "Dum cook with saffron"],
    nutrition: { calories: 580, protein: 32, carbs: 68, fat: 20 },
    cost: 14.0,
  },
  {
    id: "100",
    name: "Pani Puri",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 0,
    servings: 4,
    image: "/pani-puri.jpg",
    ingredients: [
      { id: "100-1", name: "puri shells", amount: 40, unit: "piece", category: "pantry" },
      { id: "100-2", name: "potatoes", amount: 3, unit: "whole", category: "produce" },
      { id: "100-3", name: "chickpeas", amount: 1, unit: "cup", category: "pantry" },
      { id: "100-4", name: "tamarind", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "100-5", name: "mint", amount: 1, unit: "cup", category: "produce" },
      { id: "100-6", name: "chaat masala", amount: 2, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Prepare pani", "Make filling", "Assemble and serve"],
    nutrition: { calories: 280, protein: 8, carbs: 52, fat: 6 },
    cost: 4.0,
  },
]
