import type { Recipe } from "./types"
import { calculateRecipeCost } from "./ingredient-prices"

export const sampleRecipes: Recipe[] = [
  // CLASSIC DIET (12 recipes)
  {
    id: "1",
    name: "Avocado Toast",
    category: "breakfast",
    diet: "classic",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 14, carbs: 28, fat: 18 },
    ingredients: [
      { id: "1", name: "Bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "2", name: "Avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "4", name: "Salt", amount: 1, unit: "pinch", category: "pantry" },
      { id: "5", name: "Pepper", amount: 1, unit: "pinch", category: "pantry" },
    ],
    instructions: ["Toast bread", "Mash avocados", "Fry eggs", "Assemble and serve"],
    image: "/avocado-toast.png",
  },
  {
    id: "2",
    name: "Grilled Chicken Salad",
    category: "lunch",
    diet: "classic",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 285, protein: 32, carbs: 12, fat: 12 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 2, unit: "lb", category: "meat" },
      { id: "7", name: "Mixed Greens", amount: 8, unit: "cup", category: "produce" },
      { id: "8", name: "Cherry Tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "9", name: "Cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Grill chicken", "Chop vegetables", "Toss salad", "Serve"],
    image: "/grilled-chicken-salad.png",
  },
  {
    id: "3",
    name: "Spaghetti Bolognese",
    category: "dinner",
    diet: "classic",
    prepTime: 10,
    cookTime: 45,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 520, protein: 28, carbs: 58, fat: 18 },
    ingredients: [
      { id: "12", name: "Ground Beef", amount: 2, unit: "lb", category: "meat" },
      { id: "13", name: "Spaghetti", amount: 1, unit: "lb", category: "pantry" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
      { id: "16", name: "Tomato Sauce", amount: 28, unit: "oz", category: "pantry" },
    ],
    instructions: ["Cook pasta", "Brown beef", "Simmer sauce", "Combine and serve"],
    image: "/spaghetti-bolognese-pasta.jpg",
  },
  {
    id: "4",
    name: "Pancakes with Syrup",
    category: "breakfast",
    diet: "classic",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 8, carbs: 62, fat: 10 },
    ingredients: [
      { id: "40", name: "Flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "3", name: "Eggs", amount: 2, unit: "whole", category: "dairy" },
      { id: "41", name: "Milk", amount: 1.5, unit: "cup", category: "dairy" },
      { id: "42", name: "Butter", amount: 3, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Mix batter", "Heat griddle", "Cook pancakes", "Serve with syrup"],
    image: "/fluffy-pancakes-with-maple-syrup.jpg",
  },
  {
    id: "5",
    name: "BLT Sandwich",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 18, carbs: 38, fat: 22 },
    ingredients: [
      { id: "43", name: "Bacon", amount: 8, unit: "slice", category: "meat" },
      { id: "1", name: "Bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "30", name: "Lettuce", amount: 4, unit: "leaf", category: "produce" },
      { id: "31", name: "Tomato", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Cook bacon", "Toast bread", "Assemble sandwich", "Serve"],
    image: "/blt-sandwich-with-crispy-bacon.jpg",
  },
  {
    id: "6",
    name: "Beef Tacos",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 450, protein: 24, carbs: 42, fat: 20 },
    ingredients: [
      { id: "12", name: "Ground Beef", amount: 1, unit: "lb", category: "meat" },
      { id: "44", name: "Taco Shells", amount: 8, unit: "whole", category: "pantry" },
      { id: "32", name: "Cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "30", name: "Lettuce", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Brown beef", "Warm shells", "Assemble tacos", "Serve"],
    image: "/beef-tacos-with-toppings.jpg",
  },
  {
    id: "7",
    name: "French Toast",
    category: "breakfast",
    diet: "classic",
    prepTime: 5,
    cookTime: 10,
    servings: 3,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 12, carbs: 48, fat: 11 },
    ingredients: [
      { id: "1", name: "Bread", amount: 6, unit: "slice", category: "pantry" },
      { id: "3", name: "Eggs", amount: 3, unit: "whole", category: "dairy" },
      { id: "41", name: "Milk", amount: 0.5, unit: "cup", category: "dairy" },
      { id: "45", name: "Cinnamon", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Whisk egg mixture", "Dip bread", "Cook until golden", "Serve with syrup"],
    image: "/french-toast-with-powdered-sugar.jpg",
  },
  {
    id: "8",
    name: "Club Sandwich",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 28, carbs: 44, fat: 22 },
    ingredients: [
      { id: "1", name: "Bread", amount: 6, unit: "slice", category: "pantry" },
      { id: "29", name: "Turkey Slices", amount: 6, unit: "slice", category: "meat" },
      { id: "43", name: "Bacon", amount: 4, unit: "slice", category: "meat" },
      { id: "30", name: "Lettuce", amount: 4, unit: "leaf", category: "produce" },
    ],
    instructions: ["Toast bread", "Cook bacon", "Layer ingredients", "Cut and serve"],
    image: "/triple-decker-club-sandwich.jpg",
  },
  {
    id: "9",
    name: "Meatloaf with Mashed Potatoes",
    category: "dinner",
    diet: "classic",
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 520, protein: 32, carbs: 38, fat: 24 },
    ingredients: [
      { id: "12", name: "Ground Beef", amount: 2, unit: "lb", category: "meat" },
      { id: "46", name: "Potatoes", amount: 3, unit: "lb", category: "produce" },
      { id: "3", name: "Eggs", amount: 2, unit: "whole", category: "dairy" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Mix meatloaf", "Bake", "Boil and mash potatoes", "Serve together"],
    image: "/meatloaf-with-mashed-potatoes.jpg",
  },
  {
    id: "10",
    name: "Scrambled Eggs and Toast",
    category: "breakfast",
    diet: "classic",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 16, carbs: 24, fat: 14 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "1", name: "Bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "42", name: "Butter", amount: 2, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Scramble eggs", "Toast bread", "Serve together"],
    image: "/scrambled-eggs-with-buttered-toast.jpg",
  },
  {
    id: "11",
    name: "Chicken Caesar Wrap",
    category: "lunch",
    diet: "classic",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 28, carbs: 36, fat: 18 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "6", name: "Chicken Breast", amount: 0.5, unit: "lb", category: "meat" },
      { id: "48", name: "Romaine Lettuce", amount: 2, unit: "cup", category: "produce" },
      { id: "17", name: "Parmesan Cheese", amount: 0.25, unit: "cup", category: "dairy" },
    ],
    instructions: ["Grill chicken", "Chop lettuce", "Assemble wrap", "Roll and serve"],
    image: "/chicken-caesar-wrap.png",
  },
  {
    id: "12",
    name: "Roast Chicken Dinner",
    category: "dinner",
    diet: "classic",
    prepTime: 15,
    cookTime: 75,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 42, carbs: 28, fat: 22 },
    ingredients: [
      { id: "49", name: "Whole Chicken", amount: 1, unit: "whole", category: "meat" },
      { id: "46", name: "Potatoes", amount: 2, unit: "lb", category: "produce" },
      { id: "24", name: "Carrots", amount: 4, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season chicken", "Roast with vegetables", "Rest and carve", "Serve"],
    image: "/roast-chicken-vegetables.png",
  },

  // LOW-CARB DIET (13 recipes)
  {
    id: "13",
    name: "Egg White Omelet",
    category: "breakfast",
    diet: "low-carb",
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 180, protein: 22, carbs: 6, fat: 8 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 6, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "51", name: "Mushrooms", amount: 1, unit: "cup", category: "produce" },
      { id: "32", name: "Cheese", amount: 0.25, unit: "cup", category: "dairy" },
    ],
    instructions: ["Whisk egg whites", "Sauté vegetables", "Cook omelet", "Fold and serve"],
    image: "/egg-white-omelet-with-vegetables.jpg",
  },
  {
    id: "14",
    name: "Zucchini Noodles with Pesto",
    category: "lunch",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 5,
    servings: 3,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 220, protein: 8, carbs: 12, fat: 16 },
    ingredients: [
      { id: "52", name: "Zucchini", amount: 4, unit: "whole", category: "produce" },
      { id: "53", name: "Pesto", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "17", name: "Parmesan Cheese", amount: 0.25, unit: "cup", category: "dairy" },
      { id: "8", name: "Cherry Tomatoes", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Spiralize zucchini", "Sauté lightly", "Toss with pesto", "Top with cheese"],
    image: "/zucchini-noodles-with-pesto.jpg",
  },
  {
    id: "15",
    name: "Grilled Salmon with Asparagus",
    category: "dinner",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 38, carbs: 8, fat: 18 },
    ingredients: [
      { id: "54", name: "Salmon Fillet", amount: 1.5, unit: "lb", category: "meat" },
      { id: "55", name: "Asparagus", amount: 1, unit: "lb", category: "produce" },
      { id: "11", name: "Lemon", amount: 2, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season salmon", "Grill with asparagus", "Squeeze lemon", "Serve"],
    image: "/grilled-salmon-asparagus.png",
  },
  {
    id: "16",
    name: "Greek Yogurt Bowl",
    category: "breakfast",
    diet: "low-carb",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 200, protein: 20, carbs: 15, fat: 8 },
    ingredients: [
      { id: "18", name: "Greek Yogurt", amount: 2, unit: "cup", category: "dairy" },
      { id: "56", name: "Almonds", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
      { id: "57", name: "Chia Seeds", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Layer yogurt", "Top with nuts and berries", "Sprinkle chia seeds", "Serve"],
    image: "/greek-yogurt-berries.png",
  },
  {
    id: "17",
    name: "Cauliflower Rice Stir Fry",
    category: "lunch",
    diet: "low-carb",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 180, protein: 12, carbs: 14, fat: 10 },
    ingredients: [
      { id: "58", name: "Cauliflower", amount: 1, unit: "head", category: "produce" },
      { id: "6", name: "Chicken Breast", amount: 1, unit: "lb", category: "meat" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "25", name: "Soy Sauce", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Rice cauliflower", "Stir fry chicken", "Add vegetables", "Season and serve"],
    image: "/cauliflower-rice-stir-fry.jpg",
  },
  {
    id: "18",
    name: "Steak with Broccoli",
    category: "dinner",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 42, carbs: 10, fat: 24 },
    ingredients: [
      { id: "59", name: "Steak", amount: 1.5, unit: "lb", category: "meat" },
      { id: "22", name: "Broccoli", amount: 4, unit: "cup", category: "produce" },
      { id: "42", name: "Butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "15", name: "Garlic", amount: 3, unit: "clove", category: "produce" },
    ],
    instructions: ["Season and grill steak", "Steam broccoli", "Sauté with garlic butter", "Serve"],
    image: "/grilled-steak-with-broccoli.jpg",
  },
  {
    id: "19",
    name: "Veggie Egg Muffins",
    category: "breakfast",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 140, protein: 12, carbs: 6, fat: 8 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 8, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
      { id: "32", name: "Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Whisk eggs", "Mix in vegetables", "Pour into muffin tin", "Bake and serve"],
    image: "/vegetable-egg-muffins.jpg",
  },
  {
    id: "20",
    name: "Chicken Lettuce Wraps",
    category: "lunch",
    diet: "low-carb",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 240, protein: 28, carbs: 8, fat: 12 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 1, unit: "lb", category: "meat" },
      { id: "48", name: "Romaine Lettuce", amount: 8, unit: "leaf", category: "produce" },
      { id: "26", name: "Ginger", amount: 1, unit: "tbsp", category: "produce" },
      { id: "25", name: "Soy Sauce", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Cook chicken with ginger", "Dice chicken", "Spoon into lettuce", "Serve"],
    image: "/chicken-lettuce-wraps-asian-style.jpg",
  },
  {
    id: "21",
    name: "Baked Cod with Green Beans",
    category: "dinner",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 32, carbs: 12, fat: 12 },
    ingredients: [
      { id: "60", name: "Cod Fillet", amount: 1.5, unit: "lb", category: "meat" },
      { id: "61", name: "Green Beans", amount: 1, unit: "lb", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season cod", "Bake with lemon", "Steam green beans", "Serve together"],
    image: "/baked-cod-with-green-beans.jpg",
  },
  {
    id: "22",
    name: "Protein Smoothie Bowl",
    category: "breakfast",
    diet: "low-carb",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 220, protein: 24, carbs: 18, fat: 8 },
    ingredients: [
      { id: "62", name: "Protein Powder", amount: 2, unit: "scoop", category: "pantry" },
      { id: "63", name: "Almond Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
      { id: "56", name: "Almonds", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Blend smoothie", "Pour into bowl", "Top with berries and nuts", "Serve"],
    image: "/protein-smoothie-bowl-with-toppings.jpg",
  },
  {
    id: "23",
    name: "Tuna Salad Stuffed Avocado",
    category: "lunch",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 24, carbs: 12, fat: 22 },
    ingredients: [
      { id: "64", name: "Canned Tuna", amount: 2, unit: "can", category: "pantry" },
      { id: "2", name: "Avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "33", name: "Mayonnaise", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "9", name: "Cucumber", amount: 0.5, unit: "whole", category: "produce" },
    ],
    instructions: ["Mix tuna salad", "Halve avocados", "Fill with tuna", "Serve"],
    image: "/tuna-salad-stuffed-avocado.jpg",
  },
  {
    id: "24",
    name: "Pork Chops with Cabbage",
    category: "dinner",
    diet: "low-carb",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 36, carbs: 10, fat: 22 },
    ingredients: [
      { id: "65", name: "Pork Chops", amount: 4, unit: "piece", category: "meat" },
      { id: "66", name: "Cabbage", amount: 0.5, unit: "head", category: "produce" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Sear pork chops", "Sauté cabbage and onion", "Combine", "Serve"],
    image: "/pork-chops-with-sauteed-cabbage.jpg",
  },
  {
    id: "25",
    name: "Cottage Cheese Pancakes",
    category: "breakfast",
    diet: "low-carb",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 240, protein: 20, carbs: 16, fat: 12 },
    ingredients: [
      { id: "67", name: "Cottage Cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "3", name: "Eggs", amount: 3, unit: "whole", category: "dairy" },
      { id: "68", name: "Almond Flour", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "45", name: "Cinnamon", amount: 0.5, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Blend ingredients", "Cook on griddle", "Flip when bubbly", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // KETO DIET (13 recipes)
  {
    id: "26",
    name: "Keto Bacon and Eggs",
    category: "breakfast",
    diet: "keto",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 24, carbs: 2, fat: 36 },
    ingredients: [
      { id: "43", name: "Bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "42", name: "Butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "2", name: "Avocado", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Cook bacon", "Fry eggs in butter", "Slice avocado", "Serve together"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "27",
    name: "Keto Chicken Alfredo",
    category: "lunch",
    diet: "keto",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 38, carbs: 6, fat: 34 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 1.5, unit: "lb", category: "meat" },
      { id: "69", name: "Heavy Cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "17", name: "Parmesan Cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "52", name: "Zucchini", amount: 3, unit: "whole", category: "produce" },
    ],
    instructions: ["Spiralize zucchini", "Cook chicken", "Make alfredo sauce", "Combine and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "28",
    name: "Ribeye Steak with Butter",
    category: "dinner",
    diet: "keto",
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 620, protein: 48, carbs: 0, fat: 48 },
    ingredients: [
      { id: "70", name: "Ribeye Steak", amount: 1, unit: "lb", category: "meat" },
      { id: "42", name: "Butter", amount: 3, unit: "tbsp", category: "dairy" },
      { id: "15", name: "Garlic", amount: 2, unit: "clove", category: "produce" },
      { id: "71", name: "Rosemary", amount: 2, unit: "sprig", category: "produce" },
    ],
    instructions: ["Season steak", "Sear in hot pan", "Baste with garlic butter", "Rest and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "29",
    name: "Keto Bulletproof Coffee",
    category: "breakfast",
    diet: "keto",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 2, carbs: 0, fat: 36 },
    ingredients: [
      { id: "72", name: "Coffee", amount: 1, unit: "cup", category: "pantry" },
      { id: "42", name: "Butter", amount: 1, unit: "tbsp", category: "dairy" },
      { id: "73", name: "MCT Oil", amount: 1, unit: "tbsp", category: "pantry" },
      { id: "69", name: "Heavy Cream", amount: 1, unit: "tbsp", category: "dairy" },
    ],
    instructions: ["Brew coffee", "Add butter and MCT oil", "Blend until frothy", "Serve hot"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "30",
    name: "Keto Cobb Salad",
    category: "lunch",
    diet: "keto",
    prepTime: 15,
    cookTime: 0,
    servings: 3,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 32, carbs: 8, fat: 30 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 1, unit: "lb", category: "meat" },
      { id: "43", name: "Bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "3", name: "Eggs", amount: 3, unit: "whole", category: "dairy" },
      { id: "2", name: "Avocado", amount: 1, unit: "whole", category: "produce" },
      { id: "7", name: "Mixed Greens", amount: 4, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook chicken and bacon", "Hard boil eggs", "Chop all ingredients", "Assemble salad"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "31",
    name: "Keto Salmon with Asparagus",
    category: "dinner",
    diet: "keto",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 38, carbs: 6, fat: 28 },
    ingredients: [
      { id: "54", name: "Salmon Fillet", amount: 1.5, unit: "lb", category: "meat" },
      { id: "55", name: "Asparagus", amount: 1, unit: "lb", category: "produce" },
      { id: "42", name: "Butter", amount: 3, unit: "tbsp", category: "dairy" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Season salmon", "Roast with asparagus", "Top with lemon butter", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "32",
    name: "Keto Cheese Omelet",
    category: "breakfast",
    diet: "keto",
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 26, carbs: 3, fat: 30 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 6, unit: "whole", category: "dairy" },
      { id: "32", name: "Cheese", amount: 0.5, unit: "cup", category: "dairy" },
      { id: "42", name: "Butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "50", name: "Spinach", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Whisk eggs", "Cook in butter", "Add cheese and spinach", "Fold and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "33",
    name: "Keto Burger Bowl",
    category: "lunch",
    diet: "keto",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 460, protein: 32, carbs: 8, fat: 34 },
    ingredients: [
      { id: "12", name: "Ground Beef", amount: 1.5, unit: "lb", category: "meat" },
      { id: "30", name: "Lettuce", amount: 4, unit: "cup", category: "produce" },
      { id: "32", name: "Cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "31", name: "Tomato", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Cook burger patties", "Chop lettuce", "Assemble bowl", "Top with cheese"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "34",
    name: "Keto Pork Belly",
    category: "dinner",
    diet: "keto",
    prepTime: 10,
    cookTime: 90,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 580, protein: 28, carbs: 2, fat: 50 },
    ingredients: [
      { id: "74", name: "Pork Belly", amount: 2, unit: "lb", category: "meat" },
      { id: "15", name: "Garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "25", name: "Soy Sauce", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "26", name: "Ginger", amount: 1, unit: "tbsp", category: "produce" },
    ],
    instructions: ["Score pork belly", "Season and roast", "Crisp skin", "Slice and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "35",
    name: "Keto Avocado Smoothie",
    category: "breakfast",
    diet: "keto",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 8, carbs: 10, fat: 28 },
    ingredients: [
      { id: "2", name: "Avocado", amount: 1, unit: "whole", category: "produce" },
      { id: "63", name: "Almond Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "62", name: "Protein Powder", amount: 1, unit: "scoop", category: "pantry" },
      { id: "75", name: "Stevia", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Blend all ingredients", "Add ice if desired", "Pour and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "36",
    name: "Keto Shrimp Scampi",
    category: "lunch",
    diet: "keto",
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 32, carbs: 4, fat: 22 },
    ingredients: [
      { id: "76", name: "Shrimp", amount: 1.5, unit: "lb", category: "meat" },
      { id: "42", name: "Butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "15", name: "Garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Sauté garlic in butter", "Add shrimp", "Cook until pink", "Finish with lemon"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "37",
    name: "Keto Lamb Chops",
    category: "dinner",
    diet: "keto",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 520, protein: 42, carbs: 2, fat: 38 },
    ingredients: [
      { id: "77", name: "Lamb Chops", amount: 8, unit: "piece", category: "meat" },
      { id: "71", name: "Rosemary", amount: 3, unit: "sprig", category: "produce" },
      { id: "15", name: "Garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season lamb chops", "Sear in hot pan", "Roast with herbs", "Rest and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "38",
    name: "Keto Chia Pudding",
    category: "breakfast",
    diet: "keto",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 8, carbs: 12, fat: 22 },
    ingredients: [
      { id: "57", name: "Chia Seeds", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "78", name: "Coconut Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "75", name: "Stevia", amount: 1, unit: "tsp", category: "pantry" },
      { id: "79", name: "Vanilla Extract", amount: 0.5, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Mix all ingredients", "Refrigerate overnight", "Stir and serve", "Top with berries if desired"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // FLEXITARIAN DIET (13 recipes)
  {
    id: "39",
    name: "Veggie Breakfast Burrito",
    category: "breakfast",
    diet: "flexitarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 16, carbs: 42, fat: 16 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "3", name: "Eggs", amount: 3, unit: "whole", category: "dairy" },
      { id: "80", name: "Black Beans", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Scramble eggs", "Warm beans", "Sauté peppers", "Wrap and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "40",
    name: "Mediterranean Quinoa Bowl",
    category: "lunch",
    diet: "flexitarian",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 14, carbs: 48, fat: 12 },
    ingredients: [
      { id: "81", name: "Quinoa", amount: 1, unit: "cup", category: "pantry" },
      { id: "82", name: "Chickpeas", amount: 1, unit: "can", category: "pantry" },
      { id: "9", name: "Cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "83", name: "Feta Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Cook quinoa", "Drain chickpeas", "Chop vegetables", "Assemble bowl"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "41",
    name: "Grilled Portobello Burger",
    category: "dinner",
    diet: "flexitarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 12, carbs: 38, fat: 14 },
    ingredients: [
      { id: "84", name: "Portobello Mushrooms", amount: 4, unit: "whole", category: "produce" },
      { id: "85", name: "Burger Buns", amount: 4, unit: "whole", category: "pantry" },
      { id: "30", name: "Lettuce", amount: 4, unit: "leaf", category: "produce" },
      { id: "31", name: "Tomato", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Marinate mushrooms", "Grill until tender", "Toast buns", "Assemble burgers"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "42",
    name: "Oatmeal with Fruit",
    category: "breakfast",
    diet: "flexitarian",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 8, carbs: 52, fat: 6 },
    ingredients: [
      { id: "86", name: "Oats", amount: 1, unit: "cup", category: "pantry" },
      { id: "41", name: "Milk", amount: 2, unit: "cup", category: "dairy" },
      { id: "87", name: "Banana", amount: 1, unit: "whole", category: "produce" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook oats in milk", "Slice banana", "Top with fruit", "Serve warm"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "43",
    name: "Lentil Soup",
    category: "lunch",
    diet: "flexitarian",
    prepTime: 10,
    cookTime: 35,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 240, protein: 14, carbs: 38, fat: 4 },
    ingredients: [
      { id: "88", name: "Lentils", amount: 1.5, unit: "cup", category: "pantry" },
      { id: "24", name: "Carrots", amount: 3, unit: "whole", category: "produce" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
      { id: "89", name: "Vegetable Broth", amount: 6, unit: "cup", category: "pantry" },
    ],
    instructions: ["Sauté vegetables", "Add lentils and broth", "Simmer until tender", "Season and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "44",
    name: "Baked Chicken with Sweet Potato",
    category: "dinner",
    diet: "flexitarian",
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 36, carbs: 42, fat: 12 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 1.5, unit: "lb", category: "meat" },
      { id: "90", name: "Sweet Potato", amount: 2, unit: "lb", category: "produce" },
      { id: "22", name: "Broccoli", amount: 2, unit: "cup", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season chicken", "Cube sweet potatoes", "Roast together", "Add broccoli last 15 min"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "45",
    name: "Smoothie Bowl",
    category: "breakfast",
    diet: "flexitarian",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 12, carbs: 54, fat: 8 },
    ingredients: [
      { id: "87", name: "Banana", amount: 2, unit: "whole", category: "produce" },
      { id: "20", name: "Berries", amount: 2, unit: "cup", category: "produce" },
      { id: "18", name: "Greek Yogurt", amount: 1, unit: "cup", category: "dairy" },
      { id: "19", name: "Granola", amount: 0.5, unit: "cup", category: "pantry" },
    ],
    instructions: ["Blend banana, berries, yogurt", "Pour into bowl", "Top with granola", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "46",
    name: "Caprese Sandwich",
    category: "lunch",
    diet: "flexitarian",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 16, carbs: 42, fat: 16 },
    ingredients: [
      { id: "91", name: "Ciabatta Bread", amount: 1, unit: "loaf", category: "pantry" },
      { id: "92", name: "Mozzarella", amount: 8, unit: "slice", category: "dairy" },
      { id: "31", name: "Tomato", amount: 2, unit: "whole", category: "produce" },
      { id: "93", name: "Basil", amount: 8, unit: "leaf", category: "produce" },
    ],
    instructions: ["Slice bread", "Layer mozzarella, tomato, basil", "Drizzle with balsamic", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "47",
    name: "Vegetable Pasta Primavera",
    category: "dinner",
    diet: "flexitarian",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 14, carbs: 68, fat: 12 },
    ingredients: [
      { id: "94", name: "Penne Pasta", amount: 1, unit: "lb", category: "pantry" },
      { id: "22", name: "Broccoli", amount: 2, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "8", name: "Cherry Tomatoes", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook pasta", "Sauté vegetables", "Toss together", "Top with parmesan"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "48",
    name: "Veggie Omelet",
    category: "breakfast",
    diet: "flexitarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 18, carbs: 12, fat: 18 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "51", name: "Mushrooms", amount: 1, unit: "cup", category: "produce" },
      { id: "32", name: "Cheese", amount: 0.25, unit: "cup", category: "dairy" },
    ],
    instructions: ["Whisk eggs", "Sauté vegetables", "Pour eggs over", "Fold and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "49",
    name: "Buddha Bowl",
    category: "lunch",
    diet: "flexitarian",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 16, carbs: 52, fat: 14 },
    ingredients: [
      { id: "81", name: "Quinoa", amount: 1, unit: "cup", category: "pantry" },
      { id: "90", name: "Sweet Potato", amount: 1, unit: "lb", category: "produce" },
      { id: "82", name: "Chickpeas", amount: 1, unit: "can", category: "pantry" },
      { id: "95", name: "Kale", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook quinoa", "Roast sweet potato and chickpeas", "Massage kale", "Assemble bowl"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "50",
    name: "Fish Tacos",
    category: "dinner",
    diet: "flexitarian",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 28, carbs: 38, fat: 14 },
    ingredients: [
      { id: "96", name: "White Fish", amount: 1.5, unit: "lb", category: "meat" },
      { id: "44", name: "Taco Shells", amount: 8, unit: "whole", category: "pantry" },
      { id: "66", name: "Cabbage", amount: 2, unit: "cup", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Season and grill fish", "Shred cabbage", "Warm tortillas", "Assemble tacos"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "51",
    name: "Whole Grain Waffles",
    category: "breakfast",
    diet: "flexitarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 10, carbs: 56, fat: 10 },
    ingredients: [
      { id: "97", name: "Whole Wheat Flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "3", name: "Eggs", amount: 2, unit: "whole", category: "dairy" },
      { id: "41", name: "Milk", amount: 1.5, unit: "cup", category: "dairy" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Mix waffle batter", "Cook in waffle iron", "Top with berries", "Serve with syrup"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // PALEO DIET (13 recipes)
  {
    id: "52",
    name: "Paleo Breakfast Hash",
    category: "breakfast",
    diet: "paleo",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 24, carbs: 28, fat: 20 },
    ingredients: [
      { id: "90", name: "Sweet Potato", amount: 1, unit: "lb", category: "produce" },
      { id: "6", name: "Chicken Breast", amount: 1, unit: "lb", category: "meat" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
    ],
    instructions: ["Dice sweet potato", "Cook chicken", "Sauté peppers", "Top with fried eggs"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "53",
    name: "Paleo Chicken Salad",
    category: "lunch",
    diet: "paleo",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 32, carbs: 12, fat: 16 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 1.5, unit: "lb", category: "meat" },
      { id: "98", name: "Celery", amount: 3, unit: "stalk", category: "produce" },
      { id: "56", name: "Almonds", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "99", name: "Paleo Mayo", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Shred cooked chicken", "Chop celery and almonds", "Mix with mayo", "Serve on lettuce"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "54",
    name: "Paleo Beef Stir Fry",
    category: "dinner",
    diet: "paleo",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 36, carbs: 18, fat: 24 },
    ingredients: [
      { id: "59", name: "Steak", amount: 1.5, unit: "lb", category: "meat" },
      { id: "22", name: "Broccoli", amount: 3, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "100", name: "Coconut Aminos", amount: 3, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Slice beef thin", "Stir fry vegetables", "Add beef", "Season with coconut aminos"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "55",
    name: "Paleo Banana Pancakes",
    category: "breakfast",
    diet: "paleo",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 12, carbs: 32, fat: 12 },
    ingredients: [
      { id: "87", name: "Banana", amount: 2, unit: "whole", category: "produce" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "68", name: "Almond Flour", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "45", name: "Cinnamon", amount: 1, unit: "tsp", category: "pantry" },
    ],
    instructions: ["Mash bananas", "Mix with eggs and flour", "Cook on griddle", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "56",
    name: "Paleo Tuna Salad",
    category: "lunch",
    diet: "paleo",
    prepTime: 10,
    cookTime: 0,
    servings: 3,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 28, carbs: 8, fat: 16 },
    ingredients: [
      { id: "64", name: "Canned Tuna", amount: 3, unit: "can", category: "pantry" },
      { id: "98", name: "Celery", amount: 2, unit: "stalk", category: "produce" },
      { id: "99", name: "Paleo Mayo", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "7", name: "Mixed Greens", amount: 4, unit: "cup", category: "produce" },
    ],
    instructions: ["Drain tuna", "Chop celery", "Mix with mayo", "Serve over greens"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "57",
    name: "Paleo Grilled Chicken",
    category: "dinner",
    diet: "paleo",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 42, carbs: 12, fat: 18 },
    ingredients: [
      { id: "6", name: "Chicken Breast", amount: 2, unit: "lb", category: "meat" },
      { id: "55", name: "Asparagus", amount: 1, unit: "lb", category: "produce" },
      { id: "11", name: "Lemon", amount: 2, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Marinate chicken in lemon", "Grill chicken", "Roast asparagus", "Serve together"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "58",
    name: "Paleo Egg Muffins",
    category: "breakfast",
    diet: "paleo",
    prepTime: 10,
    cookTime: 20,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 160, protein: 14, carbs: 4, fat: 10 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 8, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "43", name: "Bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "14", name: "Onion", amount: 0.5, unit: "whole", category: "produce" },
    ],
    instructions: ["Whisk eggs", "Mix in vegetables and bacon", "Pour into muffin tin", "Bake"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "59",
    name: "Paleo Shrimp Bowl",
    category: "lunch",
    diet: "paleo",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 32, carbs: 24, fat: 12 },
    ingredients: [
      { id: "76", name: "Shrimp", amount: 1.5, unit: "lb", category: "meat" },
      { id: "58", name: "Cauliflower", amount: 1, unit: "head", category: "produce" },
      { id: "2", name: "Avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Rice cauliflower", "Sauté shrimp", "Slice avocado", "Assemble bowl"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "60",
    name: "Paleo Pot Roast",
    category: "dinner",
    diet: "paleo",
    prepTime: 20,
    cookTime: 180,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 42, carbs: 24, fat: 24 },
    ingredients: [
      { id: "101", name: "Chuck Roast", amount: 3, unit: "lb", category: "meat" },
      { id: "24", name: "Carrots", amount: 6, unit: "whole", category: "produce" },
      { id: "14", name: "Onion", amount: 2, unit: "whole", category: "produce" },
      { id: "102", name: "Beef Broth", amount: 2, unit: "cup", category: "pantry" },
    ],
    instructions: ["Sear roast", "Add vegetables and broth", "Slow cook 3 hours", "Shred and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "61",
    name: "Paleo Smoothie",
    category: "breakfast",
    diet: "paleo",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 8, carbs: 42, fat: 10 },
    ingredients: [
      { id: "87", name: "Banana", amount: 2, unit: "whole", category: "produce" },
      { id: "20", name: "Berries", amount: 2, unit: "cup", category: "produce" },
      { id: "78", name: "Coconut Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "50", name: "Spinach", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Blend all ingredients", "Add ice if desired", "Pour and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "62",
    name: "Paleo Lettuce Wraps",
    category: "lunch",
    diet: "paleo",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 28, carbs: 12, fat: 14 },
    ingredients: [
      { id: "12", name: "Ground Beef", amount: 1, unit: "lb", category: "meat" },
      { id: "48", name: "Romaine Lettuce", amount: 8, unit: "leaf", category: "produce" },
      { id: "26", name: "Ginger", amount: 1, unit: "tbsp", category: "produce" },
      { id: "100", name: "Coconut Aminos", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Brown beef with ginger", "Season with coconut aminos", "Spoon into lettuce", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "63",
    name: "Paleo Baked Salmon",
    category: "dinner",
    diet: "paleo",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 38, carbs: 8, fat: 22 },
    ingredients: [
      { id: "54", name: "Salmon Fillet", amount: 1.5, unit: "lb", category: "meat" },
      { id: "22", name: "Broccoli", amount: 4, unit: "cup", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season salmon", "Bake with lemon", "Steam broccoli", "Serve together"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "64",
    name: "Paleo Sweet Potato Hash",
    category: "breakfast",
    diet: "paleo",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 16, carbs: 32, fat: 14 },
    ingredients: [
      { id: "90", name: "Sweet Potato", amount: 1.5, unit: "lb", category: "produce" },
      { id: "43", name: "Bacon", amount: 6, unit: "slice", category: "meat" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
    ],
    instructions: ["Dice sweet potato", "Cook bacon", "Sauté hash", "Top with fried eggs"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // VEGETARIAN DIET (13 recipes)
  {
    id: "65",
    name: "Veggie Scramble",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 18, carbs: 16, fat: 16 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "51", name: "Mushrooms", amount: 1, unit: "cup", category: "produce" },
      { id: "32", name: "Cheese", amount: 0.25, unit: "cup", category: "dairy" },
    ],
    instructions: ["Sauté vegetables", "Scramble eggs", "Mix together", "Top with cheese"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "66",
    name: "Veggie Wrap",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 14, carbs: 48, fat: 12 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "103", name: "Hummus", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "9", name: "Cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Spread hummus on tortilla", "Add sliced vegetables", "Roll tightly", "Slice and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "67",
    name: "Vegetarian Chili",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 16, carbs: 52, fat: 6 },
    ingredients: [
      { id: "80", name: "Black Beans", amount: 2, unit: "can", category: "pantry" },
      { id: "104", name: "Kidney Beans", amount: 1, unit: "can", category: "pantry" },
      { id: "16", name: "Tomato Sauce", amount: 28, unit: "oz", category: "pantry" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Sauté vegetables", "Add beans and sauce", "Simmer 30 minutes", "Season and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "68",
    name: "Yogurt Parfait",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 16, carbs: 42, fat: 6 },
    ingredients: [
      { id: "18", name: "Greek Yogurt", amount: 2, unit: "cup", category: "dairy" },
      { id: "19", name: "Granola", amount: 1, unit: "cup", category: "pantry" },
      { id: "20", name: "Berries", amount: 2, unit: "cup", category: "produce" },
      { id: "21", name: "Honey", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Layer yogurt in glasses", "Add granola and berries", "Drizzle honey", "Serve"],
    image: "/greek-yogurt-parfait-berries.jpg",
  },
  {
    id: "69",
    name: "Grilled Cheese Sandwich",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 5,
    cookTime: 8,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 18, carbs: 38, fat: 22 },
    ingredients: [
      { id: "1", name: "Bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "32", name: "Cheese", amount: 4, unit: "slice", category: "dairy" },
      { id: "42", name: "Butter", amount: 2, unit: "tbsp", category: "dairy" },
      { id: "31", name: "Tomato", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Butter bread", "Add cheese and tomato", "Grill until golden", "Serve hot"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "70",
    name: "Eggplant Parmesan",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 20,
    cookTime: 40,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 20, carbs: 38, fat: 22 },
    ingredients: [
      { id: "105", name: "Eggplant", amount: 2, unit: "whole", category: "produce" },
      { id: "16", name: "Tomato Sauce", amount: 24, unit: "oz", category: "pantry" },
      { id: "92", name: "Mozzarella", amount: 2, unit: "cup", category: "dairy" },
      { id: "17", name: "Parmesan Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Slice and bread eggplant", "Layer with sauce and cheese", "Bake until bubbly", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "71",
    name: "Veggie Frittata",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 260, protein: 18, carbs: 12, fat: 16 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 8, unit: "whole", category: "dairy" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
      { id: "83", name: "Feta Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Whisk eggs", "Sauté vegetables", "Pour eggs over", "Bake until set"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "72",
    name: "Black Bean Quesadilla",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 20, carbs: 52, fat: 16 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "80", name: "Black Beans", amount: 1, unit: "cup", category: "pantry" },
      { id: "32", name: "Cheese", amount: 1, unit: "cup", category: "dairy" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Mash beans", "Spread on tortilla", "Add cheese and peppers", "Grill and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "73",
    name: "Vegetable Lasagna",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 30,
    cookTime: 60,
    servings: 8,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 18, carbs: 42, fat: 16 },
    ingredients: [
      { id: "106", name: "Lasagna Noodles", amount: 1, unit: "lb", category: "pantry" },
      { id: "107", name: "Ricotta Cheese", amount: 2, unit: "cup", category: "dairy" },
      { id: "50", name: "Spinach", amount: 4, unit: "cup", category: "produce" },
      { id: "16", name: "Tomato Sauce", amount: 32, unit: "oz", category: "pantry" },
    ],
    instructions: ["Cook noodles", "Layer with cheese and vegetables", "Bake covered", "Rest and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "74",
    name: "Breakfast Burrito",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 20, carbs: 48, fat: 18 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "80", name: "Black Beans", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "32", name: "Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Scramble eggs", "Warm beans", "Fill tortilla", "Roll and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "75",
    name: "Falafel Pita",
    category: "lunch",
    diet: "vegetarian",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 16, carbs: 52, fat: 14 },
    ingredients: [
      { id: "82", name: "Chickpeas", amount: 2, unit: "can", category: "pantry" },
      { id: "108", name: "Pita Bread", amount: 4, unit: "whole", category: "pantry" },
      { id: "103", name: "Hummus", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "30", name: "Lettuce", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Make falafel patties", "Fry until golden", "Stuff in pita", "Add hummus and lettuce"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "76",
    name: "Mushroom Risotto",
    category: "dinner",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 12, carbs: 62, fat: 14 },
    ingredients: [
      { id: "109", name: "Arborio Rice", amount: 1.5, unit: "cup", category: "pantry" },
      { id: "51", name: "Mushrooms", amount: 3, unit: "cup", category: "produce" },
      { id: "89", name: "Vegetable Broth", amount: 4, unit: "cup", category: "pantry" },
      { id: "17", name: "Parmesan Cheese", amount: 0.5, unit: "cup", category: "dairy" },
    ],
    instructions: ["Sauté mushrooms", "Toast rice", "Add broth gradually", "Stir in cheese"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "77",
    name: "Blueberry Muffins",
    category: "breakfast",
    diet: "vegetarian",
    prepTime: 10,
    cookTime: 20,
    servings: 12,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 220, protein: 4, carbs: 38, fat: 6 },
    ingredients: [
      { id: "40", name: "Flour", amount: 2, unit: "cup", category: "pantry" },
      { id: "3", name: "Eggs", amount: 2, unit: "whole", category: "dairy" },
      { id: "41", name: "Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "110", name: "Blueberries", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Mix batter", "Fold in blueberries", "Fill muffin tin", "Bake until golden"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // PESCATARIAN DIET (12 recipes)
  {
    id: "78",
    name: "Smoked Salmon Bagel",
    category: "breakfast",
    diet: "pescatarian",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 24, carbs: 42, fat: 14 },
    ingredients: [
      { id: "111", name: "Bagel", amount: 2, unit: "whole", category: "pantry" },
      { id: "112", name: "Cream Cheese", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "113", name: "Smoked Salmon", amount: 4, unit: "oz", category: "meat" },
      { id: "114", name: "Capers", amount: 1, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Toast bagel", "Spread cream cheese", "Top with salmon", "Add capers"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "79",
    name: "Tuna Poke Bowl",
    category: "lunch",
    diet: "pescatarian",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 32, carbs: 48, fat: 12 },
    ingredients: [
      { id: "115", name: "Sushi Grade Tuna", amount: 1, unit: "lb", category: "meat" },
      { id: "27", name: "Rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "2", name: "Avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "116", name: "Edamame", amount: 1, unit: "cup", category: "frozen" },
    ],
    instructions: ["Cook rice", "Cube tuna", "Assemble bowl", "Drizzle with soy sauce"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "80",
    name: "Grilled Swordfish",
    category: "dinner",
    diet: "pescatarian",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 42, carbs: 12, fat: 18 },
    ingredients: [
      { id: "117", name: "Swordfish Steak", amount: 1.5, unit: "lb", category: "meat" },
      { id: "11", name: "Lemon", amount: 2, unit: "whole", category: "produce" },
      { id: "55", name: "Asparagus", amount: 1, unit: "lb", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Marinate swordfish", "Grill with lemon", "Roast asparagus", "Serve together"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "81",
    name: "Shrimp Omelet",
    category: "breakfast",
    diet: "pescatarian",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 28, carbs: 6, fat: 20 },
    ingredients: [
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "76", name: "Shrimp", amount: 0.5, unit: "lb", category: "meat" },
      { id: "32", name: "Cheese", amount: 0.25, unit: "cup", category: "dairy" },
      { id: "50", name: "Spinach", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Sauté shrimp", "Whisk eggs", "Cook omelet", "Fold and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "82",
    name: "Fish Tacos",
    category: "lunch",
    diet: "pescatarian",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 28, carbs: 38, fat: 14 },
    ingredients: [
      { id: "96", name: "White Fish", amount: 1.5, unit: "lb", category: "meat" },
      { id: "44", name: "Taco Shells", amount: 8, unit: "whole", category: "pantry" },
      { id: "66", name: "Cabbage", amount: 2, unit: "cup", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Season and grill fish", "Shred cabbage", "Warm tortillas", "Assemble tacos"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "83",
    name: "Seafood Paella",
    category: "dinner",
    diet: "pescatarian",
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 32, carbs: 58, fat: 14 },
    ingredients: [
      { id: "27", name: "Rice", amount: 2, unit: "cup", category: "pantry" },
      { id: "76", name: "Shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "118", name: "Mussels", amount: 1, unit: "lb", category: "meat" },
      { id: "119", name: "Saffron", amount: 1, unit: "pinch", category: "pantry" },
    ],
    instructions: ["Toast rice with saffron", "Add broth", "Layer seafood", "Cook until done"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "84",
    name: "Tuna Avocado Toast",
    category: "breakfast",
    diet: "pescatarian",
    prepTime: 5,
    cookTime: 5,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 24, carbs: 28, fat: 16 },
    ingredients: [
      { id: "1", name: "Bread", amount: 4, unit: "slice", category: "pantry" },
      { id: "64", name: "Canned Tuna", amount: 1, unit: "can", category: "pantry" },
      { id: "2", name: "Avocado", amount: 1, unit: "whole", category: "produce" },
      { id: "11", name: "Lemon", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Toast bread", "Mash avocado", "Mix tuna with lemon", "Assemble and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "85",
    name: "Shrimp Caesar Salad",
    category: "lunch",
    diet: "pescatarian",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 28, carbs: 18, fat: 18 },
    ingredients: [
      { id: "76", name: "Shrimp", amount: 1, unit: "lb", category: "meat" },
      { id: "48", name: "Romaine Lettuce", amount: 8, unit: "cup", category: "produce" },
      { id: "17", name: "Parmesan Cheese", amount: 0.5, unit: "cup", category: "dairy" },
      { id: "120", name: "Croutons", amount: 1, unit: "cup", category: "pantry" },
    ],
    instructions: ["Grill shrimp", "Chop lettuce", "Toss with dressing", "Top with shrimp"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "86",
    name: "Baked Halibut",
    category: "dinner",
    diet: "pescatarian",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 38, carbs: 12, fat: 14 },
    ingredients: [
      { id: "121", name: "Halibut Fillet", amount: 1.5, unit: "lb", category: "meat" },
      { id: "8", name: "Cherry Tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "15", name: "Garlic", amount: 3, unit: "clove", category: "produce" },
      { id: "10", name: "Olive Oil", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Season halibut", "Bake with tomatoes", "Roast garlic", "Serve together"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "87",
    name: "Salmon Eggs Benedict",
    category: "breakfast",
    diet: "pescatarian",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 480, protein: 28, carbs: 32, fat: 26 },
    ingredients: [
      { id: "122", name: "English Muffin", amount: 2, unit: "whole", category: "pantry" },
      { id: "113", name: "Smoked Salmon", amount: 4, unit: "oz", category: "meat" },
      { id: "3", name: "Eggs", amount: 4, unit: "whole", category: "dairy" },
      { id: "123", name: "Hollandaise Sauce", amount: 0.5, unit: "cup", category: "pantry" },
    ],
    instructions: ["Toast muffins", "Poach eggs", "Layer salmon", "Top with hollandaise"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "88",
    name: "Crab Cakes",
    category: "lunch",
    diet: "pescatarian",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 24, carbs: 22, fat: 16 },
    ingredients: [
      { id: "124", name: "Crab Meat", amount: 1, unit: "lb", category: "meat" },
      { id: "125", name: "Breadcrumbs", amount: 1, unit: "cup", category: "pantry" },
      { id: "3", name: "Eggs", amount: 2, unit: "whole", category: "dairy" },
      { id: "33", name: "Mayonnaise", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Mix crab with binders", "Form patties", "Pan fry until golden", "Serve with lemon"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "89",
    name: "Lobster Tail Dinner",
    category: "dinner",
    diet: "pescatarian",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 38, carbs: 28, fat: 18 },
    ingredients: [
      { id: "126", name: "Lobster Tail", amount: 4, unit: "piece", category: "meat" },
      { id: "42", name: "Butter", amount: 4, unit: "tbsp", category: "dairy" },
      { id: "46", name: "Potatoes", amount: 1.5, unit: "lb", category: "produce" },
      { id: "11", name: "Lemon", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Broil lobster tails", "Melt garlic butter", "Roast potatoes", "Serve with lemon"],
    image: "/placeholder.svg?height=200&width=200",
  },

  // VEGAN DIET (13 recipes)
  {
    id: "90",
    name: "Vegan Tofu Scramble",
    category: "breakfast",
    diet: "vegan",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 240, protein: 16, carbs: 18, fat: 12 },
    ingredients: [
      { id: "127", name: "Tofu", amount: 14, unit: "oz", category: "other" },
      { id: "50", name: "Spinach", amount: 2, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 1, unit: "whole", category: "produce" },
      { id: "128", name: "Nutritional Yeast", amount: 2, unit: "tbsp", category: "pantry" },
    ],
    instructions: ["Crumble tofu", "Sauté vegetables", "Mix together", "Season and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "91",
    name: "Vegan Buddha Bowl",
    category: "lunch",
    diet: "vegan",
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 14, carbs: 58, fat: 12 },
    ingredients: [
      { id: "81", name: "Quinoa", amount: 1, unit: "cup", category: "pantry" },
      { id: "90", name: "Sweet Potato", amount: 1, unit: "lb", category: "produce" },
      { id: "82", name: "Chickpeas", amount: 1, unit: "can", category: "pantry" },
      { id: "95", name: "Kale", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook quinoa", "Roast sweet potato and chickpeas", "Massage kale", "Assemble bowl"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "92",
    name: "Vegan Lentil Curry",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 16, carbs: 52, fat: 6 },
    ingredients: [
      { id: "88", name: "Lentils", amount: 1.5, unit: "cup", category: "pantry" },
      { id: "78", name: "Coconut Milk", amount: 1, unit: "can", category: "dairy" },
      { id: "129", name: "Curry Powder", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "50", name: "Spinach", amount: 3, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook lentils", "Add coconut milk and curry", "Simmer", "Stir in spinach"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "93",
    name: "Vegan Overnight Oats",
    category: "breakfast",
    diet: "vegan",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 8, carbs: 48, fat: 8 },
    ingredients: [
      { id: "86", name: "Oats", amount: 1, unit: "cup", category: "pantry" },
      { id: "63", name: "Almond Milk", amount: 1.5, unit: "cup", category: "dairy" },
      { id: "57", name: "Chia Seeds", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "87", name: "Banana", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Mix oats, milk, chia", "Refrigerate overnight", "Top with banana", "Serve cold"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "94",
    name: "Vegan Chickpea Salad",
    category: "lunch",
    diet: "vegan",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 280, protein: 12, carbs: 38, fat: 10 },
    ingredients: [
      { id: "82", name: "Chickpeas", amount: 2, unit: "can", category: "pantry" },
      { id: "9", name: "Cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "8", name: "Cherry Tomatoes", amount: 2, unit: "cup", category: "produce" },
      { id: "130", name: "Tahini", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Drain chickpeas", "Chop vegetables", "Mix with tahini dressing", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "95",
    name: "Vegan Stir Fry",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 14, carbs: 52, fat: 8 },
    ingredients: [
      { id: "127", name: "Tofu", amount: 14, unit: "oz", category: "other" },
      { id: "22", name: "Broccoli", amount: 3, unit: "cup", category: "produce" },
      { id: "23", name: "Bell Peppers", amount: 2, unit: "whole", category: "produce" },
      { id: "27", name: "Rice", amount: 2, unit: "cup", category: "pantry" },
    ],
    instructions: ["Cook rice", "Stir fry tofu", "Add vegetables", "Season and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "96",
    name: "Vegan Smoothie Bowl",
    category: "breakfast",
    diet: "vegan",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 8, carbs: 58, fat: 10 },
    ingredients: [
      { id: "87", name: "Banana", amount: 2, unit: "whole", category: "produce" },
      { id: "20", name: "Berries", amount: 2, unit: "cup", category: "produce" },
      { id: "63", name: "Almond Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "131", name: "Coconut Flakes", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Blend banana, berries, milk", "Pour into bowl", "Top with coconut", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "97",
    name: "Vegan Hummus Wrap",
    category: "lunch",
    diet: "vegan",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 340, protein: 12, carbs: 52, fat: 12 },
    ingredients: [
      { id: "47", name: "Tortilla", amount: 2, unit: "whole", category: "pantry" },
      { id: "103", name: "Hummus", amount: 0.5, unit: "cup", category: "pantry" },
      { id: "9", name: "Cucumber", amount: 1, unit: "whole", category: "produce" },
      { id: "24", name: "Carrots", amount: 2, unit: "whole", category: "produce" },
    ],
    instructions: ["Spread hummus", "Add sliced vegetables", "Roll tightly", "Slice and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "98",
    name: "Vegan Black Bean Tacos",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 14, carbs: 62, fat: 10 },
    ingredients: [
      { id: "80", name: "Black Beans", amount: 2, unit: "can", category: "pantry" },
      { id: "44", name: "Taco Shells", amount: 8, unit: "whole", category: "pantry" },
      { id: "2", name: "Avocado", amount: 2, unit: "whole", category: "produce" },
      { id: "30", name: "Lettuce", amount: 2, unit: "cup", category: "produce" },
    ],
    instructions: ["Heat beans", "Warm shells", "Mash avocado", "Assemble tacos"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "99",
    name: "Vegan Chia Pudding",
    category: "breakfast",
    diet: "vegan",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 240, protein: 6, carbs: 32, fat: 10 },
    ingredients: [
      { id: "57", name: "Chia Seeds", amount: 0.25, unit: "cup", category: "pantry" },
      { id: "63", name: "Almond Milk", amount: 1, unit: "cup", category: "dairy" },
      { id: "132", name: "Maple Syrup", amount: 2, unit: "tbsp", category: "pantry" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
    ],
    instructions: ["Mix chia, milk, syrup", "Refrigerate overnight", "Top with berries", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "100",
    name: "Vegan Pasta Marinara",
    category: "lunch",
    diet: "vegan",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 380, protein: 12, carbs: 72, fat: 6 },
    ingredients: [
      { id: "13", name: "Spaghetti", amount: 1, unit: "lb", category: "pantry" },
      { id: "16", name: "Tomato Sauce", amount: 24, unit: "oz", category: "pantry" },
      { id: "15", name: "Garlic", amount: 4, unit: "clove", category: "produce" },
      { id: "93", name: "Basil", amount: 0.25, unit: "cup", category: "produce" },
    ],
    instructions: ["Cook pasta", "Simmer sauce with garlic", "Toss together", "Top with basil"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "101",
    name: "Vegan Mushroom Stroganoff",
    category: "dinner",
    diet: "vegan",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 420, protein: 14, carbs: 62, fat: 14 },
    ingredients: [
      { id: "51", name: "Mushrooms", amount: 4, unit: "cup", category: "produce" },
      { id: "133", name: "Vegan Sour Cream", amount: 1, unit: "cup", category: "dairy" },
      { id: "134", name: "Egg Noodles", amount: 12, unit: "oz", category: "pantry" },
      { id: "14", name: "Onion", amount: 1, unit: "whole", category: "produce" },
    ],
    instructions: ["Cook noodles", "Sauté mushrooms and onion", "Add vegan sour cream", "Combine and serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "102",
    name: "Vegan Acai Bowl",
    category: "breakfast",
    diet: "vegan",
    prepTime: 5,
    cookTime: 0,
    servings: 2,
    get cost() {
      return calculateRecipeCost(this.ingredients)
    },
    nutrition: { calories: 320, protein: 6, carbs: 62, fat: 8 },
    ingredients: [
      { id: "135", name: "Acai Puree", amount: 2, unit: "pack", category: "frozen" },
      { id: "87", name: "Banana", amount: 2, unit: "whole", category: "produce" },
      { id: "20", name: "Berries", amount: 1, unit: "cup", category: "produce" },
      { id: "131", name: "Coconut Flakes", amount: 0.25, unit: "cup", category: "pantry" },
    ],
    instructions: ["Blend acai and banana", "Pour into bowl", "Top with berries and coconut", "Serve"],
    image: "/placeholder.svg?height=200&width=200",
  },
]
