export const UNIT_OPTIONS = {
  produce: [
    { value: "whole", label: "Whole" },
    { value: "piece", label: "Piece" },
    { value: "head", label: "Head" },
    { value: "bunch", label: "Bunch" },
    { value: "leaf", label: "Leaf" },
    { value: "cup", label: "Cup" },
    { value: "lb", label: "Pound (lb)" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "kg", label: "Kilogram (kg)" },
    { value: "g", label: "Gram (g)" },
  ],
  dairy: [
    { value: "cup", label: "Cup" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "ml", label: "Milliliter (ml)" },
    { value: "l", label: "Liter (l)" },
    { value: "tbsp", label: "Tablespoon" },
    { value: "tsp", label: "Teaspoon" },
    { value: "slice", label: "Slice" },
    { value: "lb", label: "Pound (lb)" },
    { value: "g", label: "Gram (g)" },
  ],
  meat: [
    { value: "lb", label: "Pound (lb)" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "kg", label: "Kilogram (kg)" },
    { value: "g", label: "Gram (g)" },
    { value: "piece", label: "Piece" },
    { value: "slice", label: "Slice" },
    { value: "whole", label: "Whole" },
  ],
  pantry: [
    { value: "cup", label: "Cup" },
    { value: "tbsp", label: "Tablespoon" },
    { value: "tsp", label: "Teaspoon" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "lb", label: "Pound (lb)" },
    { value: "g", label: "Gram (g)" },
    { value: "kg", label: "Kilogram (kg)" },
    { value: "ml", label: "Milliliter (ml)" },
    { value: "l", label: "Liter (l)" },
    { value: "can", label: "Can" },
    { value: "jar", label: "Jar" },
    { value: "package", label: "Package" },
    { value: "pinch", label: "Pinch" },
    { value: "dash", label: "Dash" },
    { value: "loaf", label: "Loaf" },
    { value: "whole", label: "Whole" },
  ],
  frozen: [
    { value: "lb", label: "Pound (lb)" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "kg", label: "Kilogram (kg)" },
    { value: "g", label: "Gram (g)" },
    { value: "cup", label: "Cup" },
    { value: "package", label: "Package" },
    { value: "bag", label: "Bag" },
  ],
  other: [
    { value: "whole", label: "Whole" },
    { value: "piece", label: "Piece" },
    { value: "cup", label: "Cup" },
    { value: "tbsp", label: "Tablespoon" },
    { value: "tsp", label: "Teaspoon" },
    { value: "oz", label: "Ounce (oz)" },
    { value: "lb", label: "Pound (lb)" },
    { value: "g", label: "Gram (g)" },
    { value: "ml", label: "Milliliter (ml)" },
  ],
}

export function getUnitsForCategory(category: string): Array<{ value: string; label: string }> {
  return UNIT_OPTIONS[category as keyof typeof UNIT_OPTIONS] || UNIT_OPTIONS.other
}
